### ISSUE TITLE
怎么在安装php选择线程版本，ts&nts

### ISSUE THREAD

**Issue by qq781548819** [oneinstack/oneinstack#192]

**Comment by oneinstack** [comment]
1. 安装前修改options.conf新增--enable-maintainer-zts参数
php_modules_options='--enable-maintainer-zts'
2. 安装php
3. 安装pthread
···
cd ~/oneinstack/src
wget http://pecl.php.net/get/pthreads-3.1.6.tgz
tar xzf pthreads-3.1.6.tgz
cd pthreads-3.1.6
/usr/local/php/bin/phpize 
./configure --with-php-config=/usr/local/php/bin/php-config
make && make install
ls  #查看有没有 pthreads.so,如果有，证明编译成功
加载pthreads
echo 'extension=pthreads.so' > /usr/local/php/etc/php.d/ext-pthreads.ini
···
3. 重载php-fpm
`service php-fpm reload
`

**Comment by kmvan** [comment]
linux下没任何必要使用TS版。
