### ISSUE TITLE
codeigniter issues

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#193]
Can u help me for setup perfectly codeigniter with lnmp stack

**Comment by oneinstack** [comment]
Add codeigniter nginx rewrite: https://github.com/oneinstack/oneinstack/commit/8de76b58b653b9b561749231f1d6d6a566d174c1

You can upgrade oneinstack:
```
~/oneinstack/upgrade.sh oneinstack
~/oneinstack/vhost.sh #rewrite choose codeigniter
```

**Comment by johnfelipe** [comment]
i have lnmp, can i upgrade to oneinstack?

**Comment by oneinstack** [comment]
```
wget mirrors.linuxeye.com/oneinstack.tar.gz
tar xzf oneinstack.tar.gz
/root/oneinstack/upgrade.sh oneinstack
/root/oneinstack/vhost.sh
```

**Comment by johnfelipe** [comment]
i have a lot of pages in that server with lnmp old stack, i have a problem may be?

**Comment by oneinstack** [comment]
No problem

**Comment by johnfelipe** [comment]
do u tell me and ensure me 18 pages major all with wordpress, https, same number with mysql with lnmp older http://159.203.93.166/phpinfo.php if upgrade to oneinstack im not loose anything?

**Comment by johnfelipe** [comment]
> do u tell me and ensure me 18 pages major all with wordpress, https, same number with mysql with lnmp older http://159.203.93.166/phpinfo.php if upgrade to oneinstack im not loose anything?

pls tell me this for my peace and traquility

**Comment by oneinstack** [comment]
Yes,The running environment does not affect.Just a script upgrade
```
wget mirrors.linuxeye.com/oneinstack.tar.gz
tar xzf oneinstack.tar.gz
cp lnmp/options.conf oneinstack/options.conf  #overwrite options.conf
/root/oneinstack/upgrade.sh oneinstack
/root/oneinstack/vhost.sh
```
