### ISSUE TITLE
where can review nginx logs and php logs

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#194]
hello pal, pls tell me path for review log errors for nginx and php
Tnks

**Comment by johnfelipe** [comment]
ok, i see nginx error is in /data/wwwlogs
But where is php error logs?

**Comment by oneinstack** [comment]
Default php error log is closed,
Open php error log:
vi /usr/local/php/etc/php.ini
```
error_reporting = E_ALL
display_errors = On
```
