### ISSUE TITLE
why cant connect using pdo

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#195]
I have this phpinfo: http://159.65.168.192/phpinfo.php

i have this mysql;

![snag-0167](https://user-images.githubusercontent.com/428820/50148423-772fb800-0286-11e9-9492-ecdd525bd4a4.png)

i have this test

	<?php
	$servername = "localhost";
	$username = "xxx";
	$database = "xxx";
	$password = "xxxx";

	//  Create a new connection to the MySQL database using PDO
	$conn = new mysqli($servername, $username, $password);

	// Check connection
	if ($conn->connect_error) {
		die("Connection failed: " . $conn->connect_error);
	} 
	echo "Connected successfully";
	?>

or using "MySQL Database connection detection"
and show me this "Unable to connect to MySql database!"

if enter with same credentials using phpmyadmin is WORKS but why cant connect?

**Comment by oneinstack** [comment]
I have this phpinfo: http://114.115.149.103/phpinfo.php
It's OK http://114.115.149.103/test.php

**Comment by johnfelipe** [comment]
then what is my problem?

**Comment by johnfelipe** [comment]
your suggestion is create a new server from scratch using oneinstack and not lnmp?

**Comment by oneinstack** [comment]
It is suggested/recommended to use OneinStack
