### ISSUE TITLE
where can fin "mysqld.sock"

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#196]
Pls tell me path for "mysqld.sock"

**Comment by johnfelipe** [comment]
this is path "/tmp/mysql.sock"?

**Comment by oneinstack** [comment]
Yes, You can check /etc/my.cnf

**Comment by johnfelipe** [comment]
but this file /tmp/mysql.sock is empty:

![snag-0168](https://user-images.githubusercontent.com/428820/50149982-a9431900-028a-11e9-883d-cebbcef9f4ff.png)

now i using this

	<?php
	$socket = '/tmp/mysqld.sock'; // or: /tmp/mysqld.sock
	$db = new mysqli('localhost', 'xxx', 'xxxxx', "xxxx", 3306, $socket);

	// Check connection
	if (mysqli_connect_errno())
	  {
	  echo "Failed to connect to MySQL: " . mysqli_connect_error();
	  }
	?> 

and show this error:

"Failed to connect to MySQL: No such file or directory"

**Comment by oneinstack** [comment]
Not /tmp/mysqld.sock, /tmp/mysql.sock is socket, Size is 0

**Comment by johnfelipe** [comment]
<?php
	$socket = '/tmp/mysql.sock'; // or: /tmp/mysqld.sock
	$db = new mysqli('localhost', 'xxxx', 'xxxxx', "xxxxxx", 3306, $socket);

	// Check connection
	if (mysqli_connect_errno())
	  {
	  echo "Failed to connect to MySQL: " . mysqli_connect_error();
	  }
	?> 

But if u view this url https://cualitativa.dap-udea.club/test.php

show me "Failed to connect to MySQL" i need your help asap i dont know what missed

**Comment by oneinstack** [comment]
mysql password wrong?

**Comment by johnfelipe** [comment]
im using same password to login with phpmyadmin, im confused, really
