### ISSUE TITLE
PHP7.2升級失敗在Debian9

### ISSUE THREAD

**Issue by ookangzheng** [oneinstack/oneinstack#200]
<img width="1110" alt="screen shot 2018-12-21 at 05 14 04" src="https://user-images.githubusercontent.com/6301735/50311230-629a2c80-04df-11e9-8493-84f9923b8eac.png">
嘗試了很多次，都是這個結果

**Comment by oneinstack** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=101657
glibc-2.26 有问题，尝试升级glibc试试

**Comment by ookangzheng** [comment]
我更新sources 去 sid ，然後
`ln -s /usr/include/locale.h /usr/include/xlocale.h`
`apt-get install -y lsb-release build-essential libssl-dev`
後來就搞定了，也不懂為何
