### ISSUE TITLE
Backup with google Drive

### ISSUE THREAD

**Issue by Aimerzz** [oneinstack/oneinstack#202]
Please Add Google drive remote back up. THX

**Comment by jazz1611** [comment]
Hello,

Please fix script backup.sh at line 245. it duplicate the transfer file WEB, not both DB & WEB
![](https://i.imgur.com/wPvBLLB.png)

**Comment by jazz1611** [comment]
hello,
backup to google drive have issues, it sometime backup only DB at day 1 or WEB at day 2. not both.

**Comment by jazz1611** [comment]
Hello,

The backup have issues, it don't delete the old WEB_*_.tgz if old more 2 or 3 days (i set). can you check it again?

Regards,

**Comment by oneinstack** [comment]
Can you  upgrade OneinStack?
`/root/oneinstack/upgrade.sh --oneinstack`

**Comment by jazz1611** [comment]
Hello,

Yes. I was upgrade the latest OneinStack but still same that.

Regards,

**Comment by jazz1611** [comment]
Hello,
Please look screenshot, which DB have remove old backup less 17&18, but WEB don't remove old backup less 17&18. I was set backup to Google Drive only and expired_days=2.
![screenshot_3](https://user-images.githubusercontent.com/1846222/52937230-22491480-3391-11e9-9ed4-3985582aa353.png)
Regards,

**Comment by oneinstack** [comment]
I try to fix it
https://github.com/oneinstack/oneinstack/commit/5757e60494ac1e7cf05a2ce683d33819bf0515d3THX,

**Comment by jazz1611** [comment]
i have upgrade oneinstack to latest version and the issues still not fix. i try set expired_days=3 and only DB work, the WEB dont work. you can see as screenshot. on Gdrive, it still sometime saved the DB or WEB, not both.
![screenshot_5](https://user-images.githubusercontent.com/1846222/53397956-07068680-39db-11e9-82a1-915707fd4bbd.png)

**Comment by oneinstack** [comment]
Does your backup destination contain Localhost?
```
grep backup_destination ./options.conf 
```
google drive  may limit upload frequency, Error:
Failed to get file: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

**Comment by jazz1611** [comment]
```
grep backup_destination ./options.conf
backup_destination=gdrive
```
yes, maybe google limit it but the backup should removed after transfer to Gdrive

**Comment by oneinstack** [comment]
The script determines that the upload is successful before deleting the Localtion but You need to request for higher Limits on the Google API. https://support.google.com/drive/answer/37603?hl=en
