### ISSUE TITLE
PHP imagick module install failed, Please contact the author!

### ISSUE THREAD

**Issue by xiaochaohasun** [oneinstack/oneinstack#206]
In file included from MagickCore/annotate.c:91:0:
MagickCore/annotate.c: In function ‘RenderFreetype’:
/usr/include/freetype2/freetype/freetype.h:801:37: error: ‘FT_ENCODING_PRC’ undeclared (first use in this function)
 #define ft_encoding_gb2312          FT_ENCODING_PRC
                                     ^
MagickCore/annotate.c:1414:23: note: in expansion of macro ‘ft_encoding_gb2312’
         encoding_type=ft_encoding_gb2312;
                       ^
/usr/include/freetype2/freetype/freetype.h:801:37: note: each undeclared identifier is reported only once for each function it appears in
 #define ft_encoding_gb2312          FT_ENCODING_PRC
                                     ^
MagickCore/annotate.c:1414:23: note: in expansion of macro ‘ft_encoding_gb2312’
         encoding_type=ft_encoding_gb2312;
                       ^
make[1]: *** [MagickCore/MagickCore_libMagickCore_7_Q16HDRI_la-annotate.lo] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by oneinstack** [comment]
OS version? 32bit 64bit?
PHP version?
imagemagick version?
imagick version?

**Comment by xiaochaohasun** [comment]
os version:CentOS Linux release 7.4.1708 (Core)   64bit
PHP version:PHP 7.1.16 
imagemagick_ver=6.9.9-40
imagick_ver=3.4.3

**Comment by oneinstack** [comment]
Try:
rm -rf /usr/local/imagemagick
Update version: More: https://github.com/oneinstack/oneinstack/raw/master/versions.txt

**Comment by xiaochaohasun** [comment]
Thank you, I have fixed this problem, it is a freetype version problem, 2.4.11 can, 2,8 can not
