### ISSUE TITLE
能否增加PHP-LDAP扩展安装选项

### ISSUE THREAD

**Issue by hihuangwei** [oneinstack/oneinstack#207]

**Comment by oneinstack** [comment]
已经新增ldap扩展：
~/oneinstack/upgrade.sh --oneinstack   #升级
~/oneinstack/install.sh --php_extensions ldap  #安装扩展
https://github.com/oneinstack/oneinstack/commit/5efca6bb4c65f6151eca79d686510789ddb0c31c

**Comment by hihuangwei** [comment]
非常感谢
