### ISSUE TITLE
Downgrade php 7.3 to 7.0 only for one application

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#212]
Is possible downgrade php 7.3 to 7.0 for one application and still 7.3 for others

**Comment by oneinstack** [comment]
You can install Second PHP version
More: https://oneinstack.com/auto/

**Comment by johnfelipe** [comment]
I don't understand how work, can u share me video or something

**Comment by johnfelipe** [comment]
root@oneinstack-ubuntu-s-6vcpu-16gb-nyc3-01:~# wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 7 --phpcache_option 1 --phpmyadmin  --db_option 2 --dbinstallmethod 1 --dbrootpwd oneinstack --pureftpd  --redis  --memcached  --iptables  --reboot
	--2019-02-21 14:27:34--  http://mirrors.linuxeye.com/oneinstack-full.tar.gz
	Resolving mirrors.linuxeye.com (mirrors.linuxeye.com)... 45.79.84.47, 2405:fd80:710:0:6eae:8bff:fe5d:a700, 2a0d:5300:10:0:1618:77ff:fe38:edb6, ...
	Connecting to mirrors.linuxeye.com (mirrors.linuxeye.com)|45.79.84.47|:80... connected.
	HTTP request sent, awaiting response... 206 Partial Content
	Length: 293339658 (280M), 48791 (48K) remaining [application/octet-stream]
	Saving to: ‘oneinstack-full.tar.gz’

	100%[++++++++++++++++++++++++++++++++++++++>] 293,339,658 --.-K/s   in 0.1s

	2019-02-21 14:27:34 (338 KB/s) - ‘oneinstack-full.tar.gz’ saved [293339658/293339658]


	gzip: stdin: decompression OK, trailing garbage ignored
	tar: Child returned status 2
	tar: Error is not recoverable: exiting now

now what?

**Comment by oneinstack** [comment]
[oneinstack-full.tar.gz]Download incomplete, Try again:
rm -f oneinstack-full.tar.gz

**Comment by johnfelipe** [comment]
done now what?

php still PHP Version 7.3.1 and i need 7.0

**Comment by oneinstack** [comment]
1. You must to upgrade OneinStack latest, You can:
```
cd oneinstack
curl http://mirrors.linuxeye.com/upgrade_oneinstack.sh | bash
```
2. install Second PHP7.0
`./install.sh --mphp_ver 70 --phpcache_option 1 --php_extensions redis --mphp_addons`
