### ISSUE TITLE
[ERROR] can't restart tomcat

### ISSUE THREAD

**Issue by parorisim** [oneinstack/oneinstack#213]
when using
`service tomcat restart`
 to restart tomcat service, the terminal shows an error:
`grep: 884(this is the tomcat pid): No such file or directory`
`/etc/init.d/tomcat: line 70: [: =: unary operator expected`

**Comment by parorisim** [comment]
tomcat_version 9.0.16
centos_7.6

**Comment by oneinstack** [comment]
I fixed https://github.com/oneinstack/oneinstack/issues/213 , You can:
```
~/oneinstack/upgrade.sh --oneinstack
/bin/cp ~/oneinstack/init.d/Tomcat-init /etc/init.d/tomcat
chkconfig tomcat on

```
