### ISSUE TITLE
MongoDB下载链接出错

### ISSUE THREAD

**Issue by badsirius** [oneinstack/oneinstack#215]
执行 `./install.sh --db_option 15 --dbinstallmethod 1 --dbrootpwd oneinstack`
输出结果为：

`Download MongoDB binary package...
--2019-03-13 17:37:33--  https://fastdl.mongodb.org/linux/mongodb-linux-i686-4.0.6.tgz
Resolving fastdl.mongodb.org (fastdl.mongodb.org)... 99.84.104.26, 99.84.104.87, 99.84.104.98, ...
Connecting to fastdl.mongodb.org (fastdl.mongodb.org)|99.84.104.26|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-13 17:37:34 ERROR 403: Forbidden.

Auto download failed! You can manually download https://fastdl.mongodb.org/linux/mongodb-linux-i686-4.0.6.tgz into the oneinstack/src directory.
Killed
--2019-03-13 17:37:35--  https://fastdl.mongodb.org/linux/mongodb-linux-i686-4.0.6.tgz.md5
root@scw-reverent-sinoussi:~/oneinstack# Resolving fastdl.mongodb.org (fastdl.mongodb.org)... 99.84.104.26, 99.84.104.87, 99.84.104.98, ...
Connecting to fastdl.mongodb.org (fastdl.mongodb.org)|99.84.104.26|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-13 17:37:35 ERROR 403: Forbidden.

Auto download failed! You can manually download https://fastdl.mongodb.org/linux/mongodb-linux-i686-4.0.6.tgz.md5 into the oneinstack/src directory.
./include/download.sh: line 15: kill: (11970) - No such process
awk: cannot open mongodb-linux-i686-4.0.6.tgz.md5 (No such file or directory)
md5sum: mongodb-linux-i686-4.0.6.tgz: No such file or directory`

应该是MongoDB官网地址变为

> https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.6.tgz

**Comment by oneinstack** [comment]
32位操作系统吗？
