### ISSUE TITLE
how can enable ext in php with easy steps

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#216]
hi dear, with very difficulties i enable calendar extension and create my own documentation

https://docs.google.com/document/d/109pATXIYSvlbx_ehj6bU5jmboBR8TXQrFSF3a9NckYQ/edit?usp=sharing

can u share me easy method for do same and other extension if i requeried?

**Comment by johnfelipe** [comment]
other method even more steps is:


## PHP Calendar Module Installation steps.


Run server with sudo user

```
sudo su
```
Go to main folder 

```
cd /
```

Go to Root folder
```
cd root
```

Move to lnmp/src folder

```
cd lnmp/src
```
Extract php-7.2.5 in /src folder

```
tar -xzf php-7.2.5.tar.gz
```
Move to php-7.2.5/ext/calendar folder 

```
cd php-7.2.5/ext/calendar
```
Check php version detail
```
/usr/local/php/bin/phpize  
```
Make configuration setting to compile calendar extension
```
./configure --with-php-config=/usr/local/php/bin/php-config
```
load calendar extension
```
make && make-install
```
Test build 
```
make test
```
run install command again 
```
make install
```

Important Info:
copy extension path as above result.
For Example (cd /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/)

Note: Every new image extensions path may be different please make sure copy it from above command result.

Move into extension folder. 
```
cd /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/
```
Add module to ini file via below command.
```
echo 'extension=calendar.so' > /usr/local/php/etc/php.d/ext-calendar.ini
```
compile php-fpm make compiled version of php
```
sudo service php-fpm restart
```
Final steps
```
Now in your browser you can run this link http://200.122.209.132/phpinfo.php when you search for calendar using Ctrl+f you will find your calendar extension easily or you can find through command line using command “php -i” it will show you same information as it showing in browser
```
i think, again, do u have simple method?

**Comment by oneinstack** [comment]
Before installation, modify options.conf file:
vi ~/oneinstack/options.conf 
`php_modules_options='--enable-calendar'`

**Comment by johnfelipe** [comment]
im talking about after installation of everything, u understand me, no before, after, for example i install everything but i need install modules additional, how do that?

**Comment by johnfelipe** [comment]
Can u help me with steps after installation?

**Comment by johnfelipe** [comment]
Pls help with this asap

**Comment by oneinstack** [comment]
https://github.com/oneinstack/oneinstack/commit/099db0cd2781a7805faccd183c1ee93bf8525f57
You can:
```
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/install.sh --php_extensions calendar

```

**Comment by d1mf** [comment]
> 
> 
> [099db0c](https://github.com/oneinstack/oneinstack/commit/099db0cd2781a7805faccd183c1ee93bf8525f57) You can:
> 
> ```
> ~/oneinstack/upgrade.sh --oneinstack
> ~/oneinstack/install.sh --php_extensions calendar
> ```

Thanks
