### ISSUE TITLE
关于 opc.php 的安全与性能隐患问题

### ISSUE THREAD

**Issue by kmvan** [oneinstack/oneinstack#217]
如果服务器已启用 opcache，且在运营中，那么此时有恶意操作不间断地 reset 缓存，服务器将会出现严重的性能问题，CPU 持续 100% 导致跑满 php-fpm，从而出现拒绝服务情况。如果时机巧合，可能会出现重复编译二进制问题，进而导致程序错误，甚至出现文件和数据混乱影响（实测可能有 2% 的几率）。

目前因为使用的是 Opcache Control Panel，这个页面是无法防止该种恶意操作的，建议临时撤销。

我打算有时间的话，就用基于x探针来制作一个 opc 控制台，并且解决恶意操作等隐患。

**Comment by fplun** [comment]
我是直接就把default那个文件夹重命名路径也改了，另外把本地的opcache也关了，服务器上的不知道咋弄

**Comment by oneinstack** [comment]
暂时只能用户主动删除这个文件了
