### ISSUE TITLE
openresty install problem

### ISSUE THREAD

**Issue by wetlyrics** [oneinstack/oneinstack#218]
options.conf
nginx_modules_options='--add-module=../ngx_devel_kit-master --add-module=../set-misc-nginx-module-master --add-module=../srcache-nginx-module-master --add-module=../redis-nginx-module-master --add-module=../redis2-nginx-module-master --add-module=../echo-nginx-module-master --add-module=../ngx_cache_purge-master --add-module=../headers-more-nginx-module-master'

install failed:)

**Comment by oneinstack** [comment]
Openresty already contains these modules
