### ISSUE TITLE
安装lnmt后bbr无法启动

### ISSUE THREAD

**Issue by HanleyCN** [oneinstack/oneinstack#222]
系统：Centos7.5 x64
安装命令：wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --tomcat_option 1 --jdk_option 2 --db_option 2 --dbinstallmethod 1 --dbrootpwd oneinstack
安装后执行lsmod | grep bbr发现没有了bbr模块，安装之前是有的

**Comment by oneinstack** [comment]
安装后 bbr相关模块加在/etc/sysctl.conf
