### ISSUE TITLE
php版本切换功能去掉了吗？

### ISSUE THREAD

**Issue by xiasf** [oneinstack/oneinstack#223]
```shell
[root@iz2zeeougc6dfkm8wqe1t2z oneinstack]# ./change_php_version.sh
-bash: ./change_php_version.sh: No such file or directory
```

https://oneinstack.com/docs/lnmpstack-image-guide/

按照文档操作，没有这个升级脚本

**Comment by oneinstack** [comment]
镜像才有！

**Comment by xiasf** [comment]
在 https://oneinstack.com/install/ 这里看教程安装的，那现在不能切换php版本了吗，只有一个升级的，但是只能升级很低的版本，我现在要从5.4切换到7.0就不行是吧
