### ISSUE TITLE
自动生成安装代码界面的一点小错误

### ISSUE THREAD

**Issue by baoang** [oneinstack/oneinstack#224]
![Image 007](https://user-images.githubusercontent.com/17093525/56936726-74de4400-6b2b-11e9-8dd1-a8a490260054.png)

如果切换为英文的，那么除了这个切换为简体中文的按钮外，其它的部分都是英文了，但是初始界面是中文，如果要给比方说美国用户看，那么这个按钮应当是English，或者Switch to English，否则他们一眼看上去全是中文，不知道这个按钮到底是干吗的了。

另外，在切换成英文界面后，底部的生成复制命令写的是COPY INSTALL COMMAND，要是改成GENERATE INSTALL COMMAND/SCRIPTS可能更好。

**Comment by oneinstack** [comment]
安装浏览器自动识别中英文，
底部命令改成GENERATE INSTALL COMMAND
THX
