### ISSUE TITLE
希望OneinStack能支持Scientific Linux

### ISSUE THREAD

**Issue by CreeperKong** [oneinstack/oneinstack#237]
我团队只认可这个发行版（基于CentOS），请问能不能提供支持啊。

**Comment by oneinstack** [comment]
可否提供测试机器？

**Comment by CreeperKong** [comment]
> 可否提供测试机器？

对了，能否支持非x86平台的Linux

**Comment by baoang** [comment]
这个版本的Linux已经停掉了吧

**Comment by CreeperKong** [comment]
CentOS7.7没出，SL7.7出了，不知道咋回事

**Comment by baoang** [comment]
> 
> 
> CentOS7.7没出，SL7.7出了，不知道咋回事

https://lists.centos.org/pipermail/centos-devel/2019-September/017693.html
https://wiki.centos.org/About/Building_8
连那么热的8都给7.7让路了

**Comment by CreeperKong** [comment]
> > CentOS7.7没出，SL7.7出了，不知道咋回事
> 
> https://lists.centos.org/pipermail/centos-devel/2019-September/017693.html
> https://wiki.centos.org/About/Building_8
> 连那么热的8都给7.7让路了

我真的无语，已经都超了既定时间了，我还是稳稳地用RHEL吧（开发者订阅了解一下）

**Comment by oneinstack** [comment]
aarch64 源码编译试试，已经支持！
