### ISSUE TITLE
可以支持PHP SNMP 拓展安装吗

### ISSUE THREAD

**Issue by hihuangwei** [oneinstack/oneinstack#242]
可以支持PHP SNMP 拓展安装吗

**Comment by oneinstack** [comment]
cd /root/oneinstack/src
tar zxvf php-5.6.40.tar.gz  # 解压已经安装的php版本
cd php-5.6.40/ext/snmp
/usr/local/php/bin/phpize
./configure --with-php-config=/usr/local/php/bin/php-config
make && make install
cd /usr/local/php/lib/php/extensions
ls  #看到no-debug-non-zts-20131226类似文件夹
cd no-debug-non-zts-20131226
ls  #查看有没有 snmp.so,如果有，证明编译成功
加载snmp
echo 'extension=snmp.so' > /usr/local/php/etc/php.d/ext-snmp.ini
