### ISSUE TITLE
upgrade openresty failed

### ISSUE THREAD

**Issue by jazz1611** [oneinstack/oneinstack#244]
hello,

i'm using Ubuntu 18.10 with Openresty v1.13.6.2. i try upgrade to latest version of Openresty but failed. there is log error

> -L/root/oneinstack/src/openresty-1.15.8.1/build/luajit-root/usr/local/openresty/luajit/lib -L/root/oneinstack/src/openresty-1.15.8.1/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -ljemalloc -Wl,-E -Wl,-E -ldl -lpthread -lcrypt -L/root/oneinstack/src/openresty-1.15.8.1/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L/root/oneinstack/src/openresty-1.15.8.1/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl /root/oneinstack/src/openresty-1.15.8.1/../pcre-8.43/.libs/libpcre.a /root/oneinstack/src/openresty-1.15.8.1/../openssl-1.1.1c/.openssl/lib/libssl.a /root/oneinstack/src/openresty-1.15.8.1/../openssl-1.1.1c/.openssl/lib/libcrypto.a -ldl -lpthread -lz \
> -Wl,-E
> make[2]: Leaving directory '/root/oneinstack/src/openresty-1.15.8.1/build/nginx-1.15.8'
> make[1]: Leaving directory '/root/oneinstack/src/openresty-1.15.8.1/build/nginx-1.15.8'
> Upgrade OpenResty failed!

**Comment by oneinstack** [comment]
```
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/upgrade.sh --openresty 1.15.8.2
```
