### ISSUE TITLE
Possible issue for cURL error 77

### ISSUE THREAD

**Issue by hezll** [oneinstack/oneinstack#246]
The default path in php.ini  is: 
**/usr/local/openssl/cert.pem**
However, the correct path should be:
**/usr/local/openssl/ssl/cert.pem**

This change can fix this issue:
cURL error 77: error setting certificate verify locations:
CAfile: /usr/local/openssl/cert.pem
CApath: none

btw:
For another comman error: cURL error 60
https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738

**Comment by oneinstack** [comment]
Hi
Thank you for the report!
I try to fix:
curl.cainfo = "/usr/local/openssl/cert.pem"
openssl.cafile = "/usr/local/openssl/cert.pem"
openssl.capath= "/usr/local/openssl/cert.pem"
Make sure you enclose the path within double quotation marks!!!

It's Ok Now?
