### ISSUE TITLE
伺服器擁有IPv6 /root/acme.sh 證書更新錯誤

### ISSUE THREAD

**Issue by ookangzheng** [oneinstack/oneinstack#251]
伺服器: Debian10, 64bit, Nginx 1.17 ,Ipv4, Ipv6 
在acme.sh debug 更新域名的時候，IPV6出現錯誤
Debug 日誌: https://privatebin.net/?7241115b3003d535#AQAGpV117ZSeinXruxF6JQ2pxooHGznVqKZULXa57Qd6

**Comment by ookangzheng** [comment]
我人在日本，常常 oneinstack.com 的官網新增 問題，會跳出 are you cheat 或者 cloudflare timeout 的畫面，沒辦法解決嗎? 很睏擾國外用戶

**Comment by oneinstack** [comment]
acme.sh 新增 --listen-v4 参数试试？
oneinstack.com 官网重新优化了dns 再看看？

**Comment by ookangzheng** [comment]
理論上，使用 vhost.sh創建 vhost之後，acme.sh 會自動更新 https 證書嗎？
您說的 `--listen-v4` 是否需要在 代碼 裡面修改，確保之後更新只用 `IPv4`
