### ISSUE TITLE
IMAP Extension

### ISSUE THREAD

**Issue by brinsleyparagao** [oneinstack/oneinstack#254]
Hello

How to install IMAP extension in latest OIS on CentOS7 ?

**Comment by oneinstack** [comment]
```
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/install.sh --php_extensions imap
```

**Comment by hqin2013** [comment]
`checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE... yes
checking for pam_start in -lpam... yes
checking for crypt in -lcrypt... yes
checking for krb5-gssapi krb5... no
configure: error: Package requirements (krb5-gssapi krb5) were not met:

No package 'krb5-gssapi' found
No package 'krb5' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables KERBEROS_CFLAGS
and KERBEROS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
PHP imap module install failed, Please contact the author! 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
[xprober.php] found
`
@oneinstack 可以帮忙看一下吗？谢谢
