### ISSUE TITLE
I MADE ONEINSTACK DOCKER FORK

### ISSUE THREAD

**Issue by centosvnc** [oneinstack/oneinstack#262]
REPO URL : https://github.com/centosvnc/punisher.git
Thanks to YEHO. The Author of Oneinstack. It was 2013 . From Now , I am Using Oneinstack.
I made a very High performence fork of Oneinstac. It Runs On Docker Container. I Modify The NGINX Config And I put Some Extra Module to Integrate REDIS Conditional Purging. I ADD 2 PHP to Load Balance. Nginx is Front End and Apache Is Backened. With WRK My Oneinstack Fork Can Handle 8.5M Concurrent User/Sec. I Modify YEHO's NGINX.conf. Made it Multi Thread Using --thread and --aio to Use Multi Threaded CPU. I tweak PHP to USE Multi Thread CPU, I use Redis fork KeyDB to use Multi Thread, I Use Tidb Multi Thread Database instead of Percona, Mysql, I Tweak Apache WORKER and php-fpm to Use Multi Thread.

I modify SYSCTL, LIMITS and CPU GOVERNOR.
IF any ONEINSTACK contributor give me permission then I can SEND the Full Source TO your E-mail. You guys can include it to your repository. I use Phusion/Baseimage and slightly modified sbin_my_init.

My Test System Was:
6 Core 12 Thread xeon E5-1650 v3 3.50 GHz/turbo 3.6
128 GB Ram
1 Gbit NIC
2*480 SSD

My Oneinstack Fork Name Is : PUNISHER.
Because It is being Designed to use your SYSTEM's Every Single bit of RESOURCE.
Multi Threaded
High performence
parallal req handling
After Certain time It will req the CPU to enable Turbo Boost and Max Turbo using CPU Governor

I am Fluent In GO, RUST, C++ and C

Thanks YEHO Make an awesome piece of Software

**Comment by oneinstack** [comment]
Nice,  repo delete ?
