### ISSUE TITLE
CentOS 8 vs CentOS 7

### ISSUE THREAD

**Issue by InternetMedicineMan** [oneinstack/oneinstack#263]
When installing OneInStack LEMP stack on CentOS 8 I've noticed the Nginx service is not accessible from the outside world for some reason. CentOS is a bit strange I can't even install screen unless I run "dnf install epel-release" first. And when looking on the server Nginx is running and listening on port 80 but from the outside world its not accessible.

I rolled the server back and installed CentOS 7 on it and everything works perfectly as always. Installs smoothly and no issues. But what's different on CentOS 8? There obviously must be some kind of changes here?

**Comment by oneinstack** [comment]
Please check the iptables configuration
```iptables -nvL```

**Comment by InternetMedicineMan** [comment]
I've reinstalled an instance of CentOs just a default Image from Linode or Vultr. I install OneInStack/LNMP and specifically tell it to NOT use iptables. I install everything and still everything is broken. I make sure to shut down any default firewall that might be running, still no good.

OneInStack/LNMP does not seem to run on a default installation of CentOs 8, at least I can't get it to work. And my problem now is that when I load it on CentOs 7 I can't get the ext-fileinfo to load for PHP 7.2 either. So OneInStack is quickly becoming useless to me.
