### ISSUE TITLE
ONEINSTACK DOCKER FORK

### ISSUE THREAD

**Issue by centosvnc** [oneinstack/oneinstack#264]
Hi,
YEHO, HERE is the Sourcecode of ONEINSTACK HIGH PERFORMENCE FORK that runs from inside Docker container
https://www.dropbox.com/s/8oyrf02s4eircan/punisher.tar.gz

Extract oneinstack-full.tar.gz. check nginx.sh in include folder.
check debian or ubuntu.sh package section
if you know ansi c then you can checkout the nginx.tar.gz and php source.
everything is commented.
This sourcecode is for developer or programmer , who is highly fluent in python , c and c++
YEHO, i believe you atleast fluent in python and C

My request to you is, please modify it as much as you can. Opensource it with your stack. so regular people who dont know code or server, they will get chance to use docker and your stack as well.

Centminmod, serverpilot, cpanel SUCKS. they do business. We love Opensource.
God bless you, your team and your EFFORT, 
respect man

**Comment by oneinstack** [comment]
Hi,
   Can you use openresty instead of nginx + lua?

**Comment by centosvnc** [comment]
Hi,
YEHO, Just question me one by one i will give you answer.

You asked me can i use openresty instead of nginx+lua??
YES, i could. Openresty has all this module built-in !!!!!!
you dont need to compile and built all this bells and whisteles. But you cant modify it's core. If you have knowledge about HTTP webserver core, then you can extract and check it's source. Because Openresty creator already modify it.
I tried and i ran the modified openresty on production with your stack. but you have to write down couple of more extra header and core file to make it multi threaded and using all the core with the linux kernel cpu governor feature besided when team openresty will release a new version you have to add more line of code to it.

That's why I use NGINX.

**Comment by centosvnc** [comment]
Yeho,
there's a WAF written by poprock
https://github.com/p0pr0ck5/lua-resty-waf.git

is it better using??
or stick with redis waf??
you wrote an article about it on your site??

**Comment by oneinstack** [comment]
Hi
Minimize the need to modify oneinstack-full.tar.gz in the archive so that it retains the latest stable version. You can modify Dockerfile use  # Add http://mirrors.linuxeye.com/oneinstack-full.tar.gz /
Why uninstall  libgd-dev in oneinstack/include/check_sw.sh ?
You don't need to modify nginx.sh, it is recommended to modify nginx_modules_options in options.conf to extend the modules you want
I have tried to use WAF https://github.com/oneinstack/ngx_lua_waf
Maybe the above is a better choice(https://github.com/p0pr0ck5/lua-resty-waf.git)

**Comment by centosvnc** [comment]
well got it.
up to you .
you can include a Docker Version of your stack on your repo.
time to time you can customize and add more feature.

thank you

**Comment by oneinstack** [comment]
Can you please merge this PR? 
You can create `docker` directory

**Comment by centosvnc** [comment]
Look, you can create a docker directory and push all the source .
if somebody comfort with docker they will use docker version and if somebody want bare metal then they will just install
