### ISSUE TITLE
java环境下nginx配置强制跳转https不生效

### ISSUE THREAD

**Issue by kukume** [oneinstack/oneinstack#265]
执行./vhost.sh选择java环境并且强制跳转https选择y，但是对应的nginx配置文件里并没有强制跳转https的代码，希望可以修复一下。

**Comment by oneinstack** [comment]
/usr/local/nginx/conf/vhost/www.example.com.conf 配置文件贴心

**Comment by kukume** [comment]
> /usr/local/nginx/conf/vhost/www.example.com.conf 配置文件贴心

作者大大能不能自动化一下，自己改有点小麻烦

**Comment by oneinstack** [comment]
测试没问题啊 你贴下你的配置文件

**Comment by kukume** [comment]
server {
  listen 80;
  listen 443 ssl http2;
  ssl_certificate /usr/local/nginx/conf/ssl/xxx.crt;
  ssl_certificate_key /usr/local/nginx/conf/ssl/xxx.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 1400;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  server_name xxx;
  access_log off;
  index index.html index.htm index.jsp;
  root /data/wwwroot/xxx;

  #error_page 404 /404.html;
  #error_page 502 /502.html;
  
  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
    expires 30d;
    access_log off;
  }
  location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
  }
  location ~ /(\.user\.ini|\.ht|\.git|\.svn|\.project|LICENSE|README\.md) {
    deny all;
  }
  location ~ {
    proxy_pass http://127.0.0.1:8080;
    include proxy.conf;
  }
}


如以上所示，没有相应的强制跳转https代码
  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
这个是强制跳转的代码吧，使用php环境创建有这行，但是java下没有
debian10

**Comment by oneinstack** [comment]
已经修复！
