### ISSUE TITLE
how can delete certificate?

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#267]
sudo su
	cd

	cd ~/oneinstack

	./vhost.sh

	What Are You Doing?
			1. Use HTTP Only
			2. Use your own SSL Certificate and Key
			3. Use Let's Encrypt to Create SSL Certificate and Key
			q. Exit
	Please input the correct option: 3

but i have an error, how can delete that certificate with all paths and folders and files?

**Comment by oneinstack** [comment]
./vhost.sh --del

**Comment by johnfelipe** [comment]
Can u share me list of all arguments and commands for you stack?

**Comment by oneinstack** [comment]
```~/oneinstack/vhost.sh --help```
