### ISSUE TITLE
PHP 7.2 Unable to load dynamic library 'fileinfo'

### ISSUE THREAD

**Issue by InternetMedicineMan** [oneinstack/oneinstack#268]
I'm trying to load PHP 7.2 with nginx from OneInStack. When I run a composer install I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/flysystem 1.0.56 -> satisfiable by league/flysystem[1.0.56].
    - league/flysystem 1.0.56 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - league/flysystem 1.0.56 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - laravel/framework v6.2.0 requires league/flysystem ^1.0.8 -> satisfiable by league/flysystem[1.0.56].
    - Installation request for laravel/framework v6.2.0 -> satisfiable by laravel/framework[v6.2.0].
```

What is strange is that I go into the PHP ini file and uncomment that library and reload and I get this error from PHP:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'fileinfo' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/fileinfo (/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/fileinfo: cannot open shared object file: No such file or directory)
```

And so I did a yum install php-devel to make sure fileinfo.so was on the system and I added the new path to the INI and restarted now I'm getting:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/fileinfo.so' (tried: /usr/lib64/php/modules/fileinfo.so (/usr/lib64/php/modules/fileinfo.so: undefined symbol: pcre_exec)
```

Why does OneInStack not seem to include this? Seems finding documentation on this is pretty difficult because everyone keeps saying it's included in anything PHP 5.6 and greater. How come this is the only installation that doesn't include it?

**Comment by InternetMedicineMan** [comment]
I've noticed from the PHP info that fileinfo was explicitly disabled but this is necessary. How to I fix this for the install:
![image](https://user-images.githubusercontent.com/689814/70404617-4a793100-1a00-11ea-97cc-412e5d7bcea4.png)

**Comment by InternetMedicineMan** [comment]
If I download the 7.2.25 source and compile the ext-fileinfo directly then it seems to work fine.

**Comment by oneinstack** [comment]
```~/oneinstack/install.sh --php_extensions fileinfo ```
