### ISSUE TITLE
源码模式安装 openssl 1.1.1d 不存在导致 nginx/openresty 安装失败

### ISSUE THREAD

**Issue by cnyyk** [oneinstack/oneinstack#270]
源码模式安装，
会提示 openssl 1.1.1d tar gz 不存在导致 nginx/openresty 安装失败。
出错同时，ssh 上去查看 oneinstack/src 目录下，确实没有这个包。
不知道是哪里下载的时候出错。

**Comment by oneinstack** [comment]
oneinstack-full.tar.gz oneinstack/src/openssl-1.1.1d.tar.gz 有这个文件啊

**Comment by cnyyk** [comment]
备注一下，是 oneinstack.tar.gz 模式下安装不会下载 1.1.1d
