### ISSUE TITLE
OpenSSL ssl_read:successs。

### ISSUE THREAD

**Issue by Denny0503** [oneinstack/oneinstack#273]
安装最新版本时，搭建php环境出现ssl的错误信息，使用旧版本（大概1.6）时候不会出现，错误如下：（不知是不是ssl版本与nginx不匹配）
OpenSSL ssl_read:successs。
同时使用let\’s encrypt申请证书时出现超时，旧版本的不会。

**Comment by oneinstack** [comment]
那个步骤出现的这个信息，可否提供截图？

**Comment by Denny0503** [comment]
> 那个步骤出现的这个信息，可否提供截图？

使用最新版本的安装工具，部署环境Apache+nginx+php7.2，环境部署没出问题。
然后部署网站metinfo，在进入后台进行检查版本更新时，提示“OpenSSL ssl_read:success”的错误信息，可能使用curl获取文件时出错。
使用旧版本的工具，大概是1.6的版本，就可以使用，没做修改，直接按照文档说明进行部署。
另外使用新版本的ssl证书生成时，会一直无法获取证书，使用旧版本的就很快成功了。

**Comment by Denny0503** [comment]
使用最新版本的安装工具，部署环境Apache+nginx+php7.2，环境部署没出问题。
然后部署网站metinfo，在进入后台进行检查版本更新时，提示“OpenSSL ssl_read:success”的错误信息，可能使用curl获取文件时出错。
使用旧版本的工具，大概是1.6的版本，就可以使用，没做修改，直接按照文档说明进行部署。
另外使用新版本的ssl证书生成时，会一直无法获取证书，使用旧版本的就很快成功了。



容 国泉
C#软件工程师（wpf、web、linux、c++）
研发部 | 深圳华天成科技有限公司
https://www.htcview.com 
17875392886 
rgq53@qq.com 
www.vcblog.top 
深圳市, 宝安区, 西乡街道 
View on： GitHub ， 码云 
 
发件人： yeho
发送时间： 2019-12-25 13:20
收件人： oneinstack/oneinstack
抄送： Denny; Author
主题： Re: [oneinstack/oneinstack] OpenSSL ssl_read:successs。 (#273)
那个步骤出现的这个信息，可否提供截图？

**Comment by Denny0503** [comment]
> 那个步骤出现的这个信息，可否提供截图？

在内网环境又部署了一遍，貌似没问题了。谢谢。可能是网站系统版本出的问题
