### ISSUE TITLE
版本号在发布的时候是不是没有改？

### ISSUE THREAD

**Issue by zhangchenglin** [oneinstack/oneinstack#275]
`https://github.com/oneinstack/oneinstack/blob/master/install.sh`

https://github.com/oneinstack/oneinstack/blob/c5de87cb0cb8b51735b3169d0779b6687343d007/install.sh#L39-L40
我通过手动下载的里面是2.1，也不知道到底是啥版本了。
`wget http://mirrors.linuxeye.com/oneinstack-full.tar.gz`
请问通过上面命令下载的是什么版本？

**Comment by oneinstack** [comment]
忘记修改install.sh 已经重新提交https://github.com/oneinstack/oneinstack/commit/913c215ce9a62f5288178de36fe461ef7315317a，感谢反馈！
