### ISSUE TITLE
Acme.sh 可不可以用IPv6 一起同時申請 SSL Cert證書嗎

### ISSUE THREAD

**Issue by ookangzheng** [oneinstack/oneinstack#277]
我的VPS有IPV4, IPv6 同時，但會出現這個錯誤
`
Let\’s Encrypt Verify error! DNS problem: NXDOMAIN looking up A for mooo.host[Sat Jan 4 16:10:07 CST 2020] Creating domain key[Sat Jan 4 16:10:07 CST 2020] The domain key is here: /root/.acme.sh/mooo.host/mooo.host.key[Sat Jan 4 16:10:07 CST 2020] Single domain=\’mooo.host\'[Sat Jan 4 16:10:07 CST 2020] Getting domain auth token for each domain[Sat Jan 4 16:10:11 CST 2020] Getting webroot for domain=\’mooo.host\'[Sat Jan 4 16:10:11 CST 2020] Verifying: mooo.host[Sat Jan 4 16:10:18 CST 2020] Pending[Sat Jan 4 16:10:21 CST 2020] mooo.host:Verify error:Invalid response from http://mooo.host/.well-known/acme-challenge/MjzLE7H0zRBSwNuXAeajJDGf7EnO6HXn14oRYLkkc0Y [2a01:4f8:c2c:36ba::1]:[Sat Jan 4 16:10:21 CST 2020] Please add \’–debug\’ or \’–log\’ to check more details.[Sat Jan 4 16:10:21 CST 2020] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.shError: Create Let\’s Encrypt SSL Certificate failed!`

我必須關閉 ipv6 才可以呢，有什麼辦法解決嗎

**Comment by oneinstack** [comment]
vhost.sh 
```290       ~/.acme.sh/acme.sh --force --listen-v4 --issue -d ${domain} ${moredomainame_D} -w ${vhostdir}``` 229行是否有```--listen-v4```,如果没有```～/oneinstack/upgrade.sh --oneinstack```

**Comment by ookangzheng** [comment]
我試一試看
