### ISSUE TITLE
vhost.sh 文件中创建listen [::]:80; 会报错 nginx: [emerg] socket() [::]:80 faile

### ISSUE THREAD

**Issue by xihuannioyj** [oneinstack/oneinstack#280]
如题   阿里云 cenOS 6.8

**Comment by oneinstack** [comment]
centos6.8 没有启用ipv6导致，已经修复：https://github.com/oneinstack/oneinstack/commit/4a90bc19294afbf9333a9f7f1c1046d4e57b3f18
请执行`~/oneinstack/upgrade.sh --oneinstack` ,之后vhost.sh绑定
