### ISSUE TITLE
GET参数只存在key而不存在value时500

### ISSUE THREAD

**Issue by juzeon** [oneinstack/oneinstack#281]
安装后发现当GET参数只存在key而不存在value时，不管访问的是否为php文件，都报500错误。

如：

/?test（500）

/?test=1（正常）

安装命令：

`wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 6 --phpcache_option 1 --php_extensions ioncube,imagick,fileinfo,imap,redis,memcached --phpmyadmin  --db_option 1 --dbinstallmethod 1 --dbrootpwd xxxxxxxxx --pureftpd  --memcached  --reboot`

同时使用addons.sh安装了ngx_lua_waf。

服务器是阿里云新加坡，Debian 10。

**Comment by juzeon** [comment]
把nginx.conf中include waf哪一行注释掉问题就解决了，应该是ngx_lua_waf出问题了！

**Comment by oneinstack** [comment]
已经修复，请执行下面命令：
```
～/oneinstack/addons.sh --uninstall --ngx_lua_waf  #卸载
～/oneinstack/addons.sh --install --ngx_lua_waf  #再安装
```
