### ISSUE TITLE
Nginx $ssl_protocol 导致，页面无限301重定向

### ISSUE THREAD

**Issue by geXingW** [oneinstack/oneinstack#282]
以下这段代码导致访问无限重定向
`if ($ssl_protocol = "") { return 301 https://$host$request_uri; }`
注掉这段代码后恢复正常，但是`Http`访问不会强制转为`Https`。

**Comment by oneinstack** [comment]
是啥程序？ 好像没其他人暴露这个问题。我刚刚测试wordpress也没这个问题

**Comment by geXingW** [comment]
我用的wordpress也是一样，好像和程序没关系，因为请求没进入程序，`$ssl_protocol`值始终为空。

**Comment by geXingW** [comment]
定位到问题了，是DNS服务器的问题
