### ISSUE TITLE
issues with SSL

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#283]
[Mon Feb  3 12:38:29 -05 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
	[Mon Feb  3 12:38:29 -05 2020] Can not init api.
	[Mon Feb  3 12:38:29 -05 2020] Creating domain key
	[Mon Feb  3 12:38:29 -05 2020] The domain key is here: /root/.acme.sh/kbsp.ciip-cis.co/kbsp.ciip-cis.co.key
	[Mon Feb  3 12:38:29 -05 2020] Single domain='kbsp.ciip-cis.co'
	[Mon Feb  3 12:38:29 -05 2020] Getting domain auth token for each domain
	[Mon Feb  3 12:38:29 -05 2020] Getting webroot for domain='kbsp.ciip-cis.co'
	[Mon Feb  3 12:38:29 -05 2020] Getting new-authz for domain='kbsp.ciip-cis.co'
	[Mon Feb  3 12:38:30 -05 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
	[Mon Feb  3 12:38:31 -05 2020] The new-authz request is ok.
	[Mon Feb  3 12:38:31 -05 2020] Error, can not get domain token entry kbsp.ciip-cis.co
	[Mon Feb  3 12:38:31 -05 2020] Please add '--debug' or '--log' to check more details.
	[Mon Feb  3 12:38:31 -05 2020] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
	Error: Create Let's Encrypt SSL Certificate failed!

How can solve?

**Comment by oneinstack** [comment]
Can not init api
Try:
```acme.sh --upgrade --force```

**Comment by Denny0503** [comment]
创建虚拟机，使用自动生成证书时无法创建虚拟机：
nginx: [emerg] invalid value "TLSv1.3" in /usr/local/nginx/conf/vhost/apidoc.vcblog.top.conf:8
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
Create virtualhost ... [FAILED]
