### ISSUE TITLE
libcurl更新导致SSL连接出现“ OpenSSL SSL_read：成功”错误

### ISSUE THREAD

**Issue by myfengstyle** [oneinstack/oneinstack#285]
php7使用curl访问https网站返回：OpenSSL SSL_read:success，使用其他环境lnmp.org、宝塔都没有这种问题，oneinstack装了好几遍都这样

**Comment by myfengstyle** [comment]
centos7.6 和7.7都不行

**Comment by myfengstyle** [comment]
好像还原libcurl受影响的版本7.67.0，看有的帖子说让降级，也不知道怎么操作：`https://forums.cpanel.net/threads/libcurl-update-causes-openssl-ssl_read-success-error-for-ssl-connections.663445/`

**Comment by oneinstack** [comment]
1. 删除curl php,
```rm -rf /usr/local/curl /usr/local/php```
2. 修改versions.txt curl_ver=7.66.0
3. 重装php试试
