### ISSUE TITLE
invalid value "TLSv1.3"

### ISSUE THREAD

**Issue by Denny0503** [oneinstack/oneinstack#286]
创建虚拟机，使用自动生成证书时无法创建虚拟机：
nginx: [emerg] invalid value "TLSv1.3" in /usr/local/nginx/conf/vhost/apidoc.vcblog.top.conf:8
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
Create virtualhost ... [FAILED]

**Comment by Denny0503** [comment]
脚本版本从1.6升级到2.2后，创建虚拟机出错

**Comment by oneinstack** [comment]
nginx先升级下
