### ISSUE TITLE
php5.6 与oneinstack 默认mysql 8的配置有冲突

### ISSUE THREAD

**Issue by moxuanyuan** [oneinstack/oneinstack#293]
php5.6 连mysql 8 提示“Server sent charset unknown to the client”。
php 7则没有问题。网上找了一下，解决了，需要修改my.cnf
参考 https://www.jianshu.com/p/d5d8e825ebda

 [client]
default-character-set=utf8

[mysql]
default-character-set=utf8

[mysqld]
collation-server = utf8_unicode_ci
character-set-server = utf8
default_authentication_plugin = mysql_native_password

**Comment by oneinstack** [comment]
```
[client]
default-character-set=utf8
```
改成：
```
[client]
default-character-set=utf8mb4
```
这样是否正常？

**Comment by moxuanyuan** [comment]
> ```
> [client]
> default-character-set=utf8
> ```
> 
> 改成：
> 
> ```
> [client]
> default-character-set=utf8mb4
> ```
> 
> 这样是否正常？

可以

**Comment by oneinstack** [comment]
Fixed!
