### ISSUE TITLE
checking for zlib library ... not found

### ISSUE THREAD

**Issue by yangliuan** [oneinstack/oneinstack#298]
./configure: error: the HTTP gzip module requires the zlib library.
You can either disable the module by using --without-http_gzip_module
option, or install the zlib library into the system, or build the zlib library
statically from the source with nginx by using --with-zlib=<path> option.

make: *** No rule to make target 'build', needed by 'default'.  Stop.
Nginx install failed, Please Contact the author! 
Killed

**Comment by oneinstack** [comment]
yum源没有配置好吧，执行：
```
yum install zlib-devel
```
