### ISSUE TITLE
php 7.4 gd库 不支持webp

### ISSUE THREAD

**Issue by koalang** [oneinstack/oneinstack#301]
添加了--with-webp参数重新编译php
报错
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: /usr/local/lib/libwebp.a(thread_utils.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1

**Comment by oneinstack** [comment]
libwebp-devel依赖是否安装？ ```yum -y install libwebp-devel```

**Comment by koalang** [comment]
> libwebp-devel依赖是否安装？ `yum -y install libwebp-devel`
感谢回答。
Package libwebp-devel-0.3.0-7.el7.x86_64 already installed and latest version
已经安装了，还是不行。
后来php先不编译-enable-gd，再进入php-7.4.5/ext/gd单独编译gd，php.ini中添加extension=gd.so
可以了。
