### ISSUE TITLE
iptable和centos7.3以上版本自带firewalld冲突，导致安装完成后无法连接ssh

### ISSUE THREAD

**Issue by samkong97** [oneinstack/oneinstack#304]
在服务器上安装了这个，发现重启后ssh连不上
Could not connect to xxx' (port 21): Connection failed.
服务器安全组是打开的，没有问题。
多次尝试后发现，推测是oneinstack自带的iptable和centos7.3之后的firewalld冲突
另外安装的时候会有一个报错
grep: /etc/sysconfig/iptables: No such file or directory

解决方案：
只能在安装完成后手动firewall放行端口，可以正常连接ssh

**Comment by samkong97** [comment]
已经好了，不知道什么原因

**Comment by samkong97** [comment]
问题发生在重启之后，阿里云轻量服务器。

**Comment by oneinstack** [comment]
默认禁用了firewalld

**Comment by samkong97** [comment]
补充下另一个潜在问题，阿里云轻量iptables和服务器的网卡绑定，安装后使用ifconfig查看发现eth0不见了。导致服务器失联

**Comment by jiao808813** [comment]
轻量服务器同样问题
