### ISSUE TITLE
Software update & PHP build issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by kaneawk** [oneinstack/oneinstack#305]
1. Part of software should be up to date:

argon2: up to 20190702
libzip: 1.6.1
icu4c: 67_1
libiconv: 1.16

2. openssl 1.0.2 should be abandoned, No one new programs depend on this old-stuff anymore.

3. Because some unknown reason, Ubuntu 20.04 should remove `--enable-intl` then you can build successful, this is a very difficult problem, I don't know how to solve it. :(

**Comment by eallion** [comment]
same iisue

**Comment by oneinstack** [comment]
Try again
