### ISSUE TITLE
nginx + ngx_lua_waf报错

### ISSUE THREAD

**Issue by wloot** [oneinstack/oneinstack#308]
```
lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file '/usr/local/nginx/conf/waf/resty/core.lua'
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
```

**Comment by oneinstack** [comment]
`Nginx -V`贴出来看下

**Comment by wloot** [comment]
> `Nginx -V`贴出来看下
```
nginx version: nginx/1.18.0
built by gcc 8.3.0 (Debian 8.3.0-6)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=../openssl-1.1.1g --with-pcre=../pcre-8.44 --with-pcre-jit --with-ld-opt=-ljemalloc --add-module=../ngx_brotli --with-ld-opt=-Wl,-rpath,/usr/local/lib --add-module=../lua-nginx-module --add-module=../ngx_devel_kit
```
自己有手动添加brotli模块

**Comment by oneinstack** [comment]
默认waf没有加载resty.core 。。

**Comment by wloot** [comment]
> 默认waf没有加载resty.core 。。

呃 这个是哪里的问题呢? waf配置我没有改动。

**Comment by oneinstack** [comment]
参考：https://github.com/openresty/lua-nginx-module/issues/1509
try to add lua_load_resty_core off; into http {} block of nginx.conf. ？

**Comment by kulokai** [comment]
遇到相同的问题 try to add lua_load_resty_core off; 无法解决

**Comment by kulokai** [comment]
[root@nginx-lua sbin]# ./nginx
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /usr/local/nginx/conf/nginx.conf:35
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so') in /usr/local/nginx/conf/nginx.conf:124

**Comment by kulokai** [comment]
引入ngx_lua v0.10.16之前的版本 解决问题
