### ISSUE TITLE
ubuntu 20.04 php无法安装

### ISSUE THREAD

**Issue by mark0325** [oneinstack/oneinstack#309]
ubuntu20.04(wsl)无法安装php，Ubuntu 18(wsl) 正常
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isUAlphabetic':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:587: undefined reference to `u_isUAlphabetic_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isJavaIDPart':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:614: undefined reference to `u_isJavaIDPart_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isIDIgnorable':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:612: undefined reference to `u_isIDIgnorable_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isJavaIDStart':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:613: undefined reference to `u_isJavaIDStart_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isbase':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:608: undefined reference to `u_isbase_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isMirrored':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:609: undefined reference to `u_isMirrored_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isIDStart':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:610: undefined reference to `u_isIDStart_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isIDPart':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:611: undefined reference to `u_isIDPart_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isblank':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:600: undefined reference to `u_isblank_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isdefined':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:601: undefined reference to `u_isdefined_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isspace':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:602: undefined reference to `u_isspace_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isJavaSpaceChar':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:603: undefined reference to `u_isJavaSpaceChar_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isWhitespace':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:604: undefined reference to `u_isWhitespace_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_iscntrl':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:605: undefined reference to `u_iscntrl_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isISOControl':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:606: undefined reference to `u_isISOControl_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isprint':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:607: undefined reference to `u_isprint_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isULowercase':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:588: undefined reference to `u_isULowercase_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isUUppercase':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:589: undefined reference to `u_isUUppercase_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isUWhiteSpace':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:590: undefined reference to `u_isUWhiteSpace_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_islower':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:591: undefined reference to `u_islower_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isupper':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:592: undefined reference to `u_isupper_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_istitle':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:593: undefined reference to `u_istitle_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isdigit':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:594: undefined reference to `u_isdigit_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isalpha':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:595: undefined reference to `u_isalpha_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isalnum':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:596: undefined reference to `u_isalnum_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isxdigit':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:597: undefined reference to `u_isxdigit_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_ispunct':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:598: undefined reference to `u_ispunct_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_isgraph':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:599: undefined reference to `u_isgraph_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_getIntPropertyValue':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:126: undefined reference to `u_getIntPropertyValue_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_hasBinaryProperty':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:107: undefined reference to `u_hasBinaryProperty_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_digit':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:474: undefined reference to `u_digit_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_charAge':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:515: undefined reference to `u_charAge_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_charMirror':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:659: undefined reference to `u_charMirror_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_tolower':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:660: undefined reference to `u_tolower_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_toupper':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:661: undefined reference to `u_toupper_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_totitle':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:662: undefined reference to `u_totitle_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_getBidiPairedBracket':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:664: undefined reference to `u_getBidiPairedBracket_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_foldCase':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:445: undefined reference to `u_foldCase_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_getFC_NFKC_Closure':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:556: undefined reference to `u_getFC_NFKC_Closure_63'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:562: undefined reference to `u_getFC_NFKC_Closure_63'
/bin/ld: ext/intl/uchar/uchar.o: in function `zim_IntlChar_enumCharNames':
/root/oneinstack/src/php-7.4.6/ext/intl/uchar/uchar.c:341: undefined reference to `u_enumCharNames_63'
/bin/ld: ext/intl/spoofchecker/spoofchecker_class.o: in function `spoofchecker_object_destroy':
/root/oneinstack/src/php-7.4.6/ext/intl/spoofchecker/spoofchecker_class.c:179: undefined reference to `uspoof_close_63'
/bin/ld: ext/intl/spoofchecker/spoofchecker_class.o: in function `spoofchecker_clone_obj':
/root/oneinstack/src/php-7.4.6/ext/intl/spoofchecker/spoofchecker_class.c:124: undefined reference to `uspoof_clone_63'
/bin/ld: ext/intl/intl_convertcpp.o: in function `intl_stringFromChar(icu_63::UnicodeString&, char*, unsigned long, UErrorCode*)':
/root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:38: undefined reference to `icu_63::UnicodeString::getBuffer(int)'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:41: undefined reference to `u_strFromUTF8WithSub_63'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:44: undefined reference to `icu_63::UnicodeString::releaseBuffer(int)'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:30: undefined reference to `icu_63::UnicodeString::setToBogus()'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:46: undefined reference to `icu_63::UnicodeString::setToBogus()'
/bin/ld: ext/intl/intl_convertcpp.o: in function `intl_charFromString(icu_63::UnicodeString const&, UErrorCode*)':
/root/oneinstack/src/php-7.4.6/ext/intl/intl_convertcpp.cpp:77: undefined reference to `u_strToUTF8WithSub_63'
/bin/ld: ext/xmlrpc/libxmlrpc/encodings.o: in function `convert':
/root/oneinstack/src/php-7.4.6/ext/xmlrpc/libxmlrpc/encodings.c:63: undefined reference to `libiconv_open'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/xmlrpc/libxmlrpc/encodings.c:70: undefined reference to `libiconv'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/xmlrpc/libxmlrpc/encodings.c:86: undefined reference to `libiconv_close'
/bin/ld: /root/oneinstack/src/php-7.4.6/ext/xmlrpc/libxmlrpc/encodings.c:86: undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
make: *** [Makefile:290: sapi/cli/php] Error 1
PHP install failed, Please Contact the author!

**Comment by eallion** [comment]
同样的报错。
临时的解决办法：（ Ubuntu 20.04 可用）
`~/oneinstack/include/php-7.4.sh`
大概在 114 行和 125 行删掉：
`--enable-intl`
然后单独安装 PHP7.4
`./install.sh --php_option 9 --phpcache_option 1`

**Comment by oneinstack** [comment]
我测试似乎没有问题

**Comment by mark0325** [comment]
@oneinstack  桌面版？还是服务器版的，我是在桌面版 和 windows wsl下测试的

**Comment by eallion** [comment]
> 我测试似乎没有问题

全新安装的桌面版不行。

**Comment by oneinstack** [comment]
测试server版本

**Comment by xslingcn** [comment]
在Ubuntu 20.04 Server上也遇到了无法安装的问题
控制台报错输出:[https://pastebin.com/TWQBEt7M](url)
这是所用的自动安装命令:
`wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 9 --phpcache_option 1 --php_tion 1 --php_extensions fileinfo,imap,redis,memcache --phpmyadmin  --db_option 1 --dbinstallmethod 1 --dbrootpwd my_password --pureftpd  --redis  --memcached  --iptables  --reboot 
`

**Comment by cnwyx** [comment]
@oneinstack 
ubuntu官方下载server20.04 未做任何改动直接安装oneinstack
php7.4报错与楼主相同 同批机器的centos8正常 在ubuntu server20里报错 多次编译错误相同
搜索了下国内有其他lnmp也遇到这个问题 大概是说libiconv目录问题
重新编译了libiconv 做了对应目录软连接 ubuntu php7.4仍然报错
按照楼上朋友@eallion 的方法去掉intl扩展后 不报错了

**Comment by samshuai** [comment]
同样的问题，使用了@eallion 的方法安装成功。但是当我手动编译安装intl模块的时候报错：
![image](https://user-images.githubusercontent.com/1312406/84803062-0eb8c700-b034-11ea-929c-6c10cef7db0f.png)

**Comment by oneinstack** [comment]
新系统重新安装编译看看？

**Comment by monsterxcn** [comment]
试了全新的编译也不行，DigitalOcean 新开的 Ubuntu 20.04 LTS，执行了初次更新后开始编译，也出现了楼主一样的错误。

按照 @eallion 去掉 intl 的方法后安装不报错。

这是错误编译之前的信息：


```
root@Tingle:~# sudo apt update
root@Tingle:~# apt list --upgradable
Listing... Done
accountsservice/focal-updates 0.6.55-0ubuntu12~20.04.1 amd64 [upgradable from: 0.6.55-0ubuntu11]
alsa-ucm-conf/focal-updates 1.2.2-1ubuntu0.1 all [upgradable from: 1.2.2-1]
apparmor/focal-updates 2.13.3-7ubuntu5.1 amd64 [upgradable from: 2.13.3-7ubuntu5]
apport/focal-updates 2.20.11-0ubuntu27.3 all [upgradable from: 2.20.11-0ubuntu27]
bind9-dnsutils/focal-updates,focal-security 1:9.16.1-0ubuntu2.2 amd64 [upgradable from: 1:9.16.1-0ubuntu2]
bind9-host/focal-updates,focal-security 1:9.16.1-0ubuntu2.2 amd64 [upgradable from: 1:9.16.1-0ubuntu2]
bind9-libs/focal-updates,focal-security 1:9.16.1-0ubuntu2.2 amd64 [upgradable from: 1:9.16.1-0ubuntu2]
busybox-initramfs/focal-updates 1:1.30.1-4ubuntu6.1 amd64 [upgradable from: 1:1.30.1-4ubuntu6]
busybox-static/focal-updates 1:1.30.1-4ubuntu6.1 amd64 [upgradable from: 1:1.30.1-4ubuntu6]
ca-certificates/focal-updates,focal-security 20190110ubuntu1.1 all [upgradable from: 20190110ubuntu1]
dbus-user-session/focal-updates,focal-security 1.12.16-2ubuntu2.1 amd64 [upgradable from: 1.12.16-2ubuntu2]
dbus/focal-updates,focal-security 1.12.16-2ubuntu2.1 amd64 [upgradable from: 1.12.16-2ubuntu2]
fwupd-signed/focal-updates,focal-security 1.27.1ubuntu1+1.3.9-4ubuntu0.1 amd64 [upgradable from: 1.27+1.3.9-4]
fwupd/focal-updates,focal-security 1.3.9-4ubuntu0.1 amd64 [upgradable from: 1.3.9-4]
gir1.2-glib-2.0/focal-updates 1.64.1-1~ubuntu20.04.1 amd64 [upgradable from: 1.64.0-2]
grub-efi-amd64-signed/focal-updates 1.142.1+2.04-1ubuntu26 amd64 [upgradable from: 1.142+2.04-1ubuntu26]
initramfs-tools-bin/focal-updates 0.136ubuntu6.1 amd64 [upgradable from: 0.136ubuntu6]
initramfs-tools-core/focal-updates 0.136ubuntu6.1 all [upgradable from: 0.136ubuntu6]
initramfs-tools/focal-updates 0.136ubuntu6.1 all [upgradable from: 0.136ubuntu6]
libaccountsservice0/focal-updates 0.6.55-0ubuntu12~20.04.1 amd64 [upgradable from: 0.6.55-0ubuntu11]
libapparmor1/focal-updates 2.13.3-7ubuntu5.1 amd64 [upgradable from: 2.13.3-7ubuntu5]
libdbus-1-3/focal-updates,focal-security 1.12.16-2ubuntu2.1 amd64 [upgradable from: 1.12.16-2ubuntu2]
libfwupd2/focal-updates,focal-security 1.3.9-4ubuntu0.1 amd64 [upgradable from: 1.3.9-4]
libfwupdplugin1/focal-updates,focal-security 1.3.9-4ubuntu0.1 amd64 [upgradable from: 1.3.9-4]
libgirepository-1.0-1/focal-updates 1.64.1-1~ubuntu20.04.1 amd64 [upgradable from: 1.64.0-2]
libgnutls30/focal-updates,focal-security 3.6.13-2ubuntu1.1 amd64 [upgradable from: 3.6.13-2ubuntu1]
libjson-c4/focal-updates,focal-security 0.13.1+dfsg-7ubuntu0.3 amd64 [upgradable from: 0.13.1+dfsg-7ubuntu0.1]
libnetplan0/focal-updates 0.99-0ubuntu3~20.04.2 amd64 [upgradable from: 0.99-0ubuntu3~20.04.1]
libnss-systemd/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
libpam-systemd/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
libproxy1v5/focal-updates 0.4.15-10ubuntu1 amd64 [upgradable from: 0.4.15-10]
libsqlite3-0/focal-updates,focal-security 3.31.1-4ubuntu0.1 amd64 [upgradable from: 3.31.1-4]
libsystemd0/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
libudev1/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
linux-headers-generic/focal-updates,focal-security 5.4.0.37.40 amd64 [upgradable from: 5.4.0.29.34]
linux-headers-virtual/focal-updates,focal-security 5.4.0.37.40 amd64 [upgradable from: 5.4.0.29.34]
linux-image-virtual/focal-updates,focal-security 5.4.0.37.40 amd64 [upgradable from: 5.4.0.29.34]
linux-virtual/focal-updates,focal-security 5.4.0.37.40 amd64 [upgradable from: 5.4.0.29.34]
netplan.io/focal-updates 0.99-0ubuntu3~20.04.2 amd64 [upgradable from: 0.99-0ubuntu3~20.04.1]
open-iscsi/focal-updates 2.0.874-7.1ubuntu6.1 amd64 [upgradable from: 2.0.874-7.1ubuntu6]
openssh-client/focal-updates 1:8.2p1-4ubuntu0.1 amd64 [upgradable from: 1:8.2p1-4]
openssh-server/focal-updates 1:8.2p1-4ubuntu0.1 amd64 [upgradable from: 1:8.2p1-4]
openssh-sftp-server/focal-updates 1:8.2p1-4ubuntu0.1 amd64 [upgradable from: 1:8.2p1-4]
python3-apport/focal-updates 2.20.11-0ubuntu27.3 all [upgradable from: 2.20.11-0ubuntu27]
python3-problem-report/focal-updates 2.20.11-0ubuntu27.3 all [upgradable from: 2.20.11-0ubuntu27]
python3-update-manager/focal-updates 1:20.04.10.1 all [upgradable from: 1:20.04.10]
systemd-sysv/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
systemd-timesyncd/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
systemd/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
tzdata/focal-updates,focal-security 2020a-0ubuntu0.20.04 all [upgradable from: 2019c-3ubuntu1]
ubuntu-minimal/focal-updates 1.450.1 amd64 [upgradable from: 1.450]
ubuntu-server/focal-updates 1.450.1 amd64 [upgradable from: 1.450]
ubuntu-standard/focal-updates 1.450.1 amd64 [upgradable from: 1.450]
udev/focal-updates 245.4-4ubuntu3.1 amd64 [upgradable from: 245.4-4ubuntu3]
update-manager-core/focal-updates 1:20.04.10.1 all [upgradable from: 1:20.04.10]
 ......

root@Tingle:~# sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-headers-5.4.0-37 linux-headers-5.4.0-37-generic linux-image-5.4.0-37-generic linux-modules-5.4.0-37-generic
The following packages will be upgraded:
  accountsservice alsa-ucm-conf apparmor apport bind9-dnsutils bind9-host bind9-libs busybox-initramfs busybox-static
  ca-certificates dbus dbus-user-session fwupd fwupd-signed gir1.2-glib-2.0 grub-efi-amd64-signed initramfs-tools
  initramfs-tools-bin initramfs-tools-core libaccountsservice0 libapparmor1 libdbus-1-3 libfwupd2 libfwupdplugin1
  libgirepository-1.0-1 libgnutls30 libjson-c4 libnetplan0 libnss-systemd libpam-systemd libproxy1v5 libsqlite3-0
  libsystemd0 libudev1 linux-headers-generic linux-headers-virtual linux-image-virtual linux-virtual netplan.io
  open-iscsi openssh-client openssh-server openssh-sftp-server python3-apport python3-problem-report
  python3-update-manager systemd systemd-sysv systemd-timesyncd tzdata ubuntu-minimal ubuntu-server ubuntu-standard
  udev update-manager-core
55 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 51.4 MB of archives.
After this operation, 170 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
 ......

root@Tingle:~# uname -a
Linux Tingle 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@Tingle:~# wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz
root@Tingle:~# tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh

#######################################################################
#       OneinStack for CentOS/RedHat 6+ Debian 8+ and Ubuntu 14+      #
#       For more information please visit https://oneinstack.com      #
#######################################################################
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-9 gcc-9 gcc-9-base libasan5 libatomic1 libbinutils
  libc-dev-bin libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0 libgcc-9-dev libgomp1 libisl22 libitm1 liblsan0
  libmpc3 libquadmath0 libtsan0 libubsan1 linux-libc-dev manpages-dev
Suggested packages:
  binutils-doc cpp-doc gcc-9-locales gcc-multilib make autoconf automake libtool flex bison gdb gcc-doc gcc-9-multilib
  gcc-9-doc glibc-doc
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-9 gcc gcc-9 gcc-9-base libasan5 libatomic1 libbinutils
  libc-dev-bin libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0 libgcc-9-dev libgomp1 libisl22 libitm1 liblsan0
  libmpc3 libquadmath0 libtsan0 libubsan1 linux-libc-dev manpages-dev
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
 ......
```

附上 [install.log](https://raw.githubusercontent.com/monsterxcn/MyBucket/master/issue/install.log)，如果 debug 需要的话。

**Comment by betaxab** [comment]
https://github.com/oneinstack/oneinstack/issues/305

**Comment by oneinstack** [comment]
已经修复，如下执行：
```
rm -f ~/.oneinstack
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/install.sh --php_option 9
```

**Comment by monsterxcn** [comment]
> 已经修复，如下执行：
> 
> ```
> rm -f ~/.oneinstack
> ~/oneinstack/upgrade.sh --oneinstack
> ~/oneinstack/install.sh --php_option 9
> ```

👍，现在没报错问题了。
