### ISSUE TITLE
centos更新oniguruma后 php无法启动

### ISSUE THREAD

**Issue by cnwyx** [oneinstack/oneinstack#312]
20200620 centos yum升级  
oniguruma从5.9.5升到了6.8.2

`Jun 18 06:35:49 Installed: oniguruma-5.9.5-3.el7.x86_64
Jun 18 06:35:50 Installed: oniguruma-devel-5.9.5-3.el7.x86_64`

`Jun 20 03:40:11 Updated: oniguruma-6.8.2-1.el7.x86_64
Jun 20 03:40:11 Updated: oniguruma-devel-6.8.2-1.el7.x86_64`

升级后php-fpm启动失败
`/usr/local/php/sbin/php-fpm: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory`

/usr/lib64/ 下 有libonig.so  libonig.so.5  libonig.so.5.0.0 没有libonig.so.2

暂时把so链到so.2先用了

**Comment by oneinstack** [comment]
先升级再安装应该不会有问题
