### ISSUE TITLE
Let s Encrypt证书到期过后会自动续约吗

### ISSUE THREAD

**Issue by moosen2012** [oneinstack/oneinstack#313]
使用vhost.sh新增站点，采用lets encrypt证书，那么Let s Encrypt证书到期过后会自动续约吗，还是需要手动续约？

**Comment by August2012** [comment]
不修改nginx配置 中的 root 目录，就可以自动续签。否则续签会失败。

**Comment by moosen2012** [comment]
手动续约是否有简单教程，谢谢

**Comment by moosen2012** [comment]
> 不修改nginx配置 中的 root 目录，就可以自动续签。否则续签会失败。

手动续约是否有简单教程，谢谢

**Comment by August2012** [comment]
> > 不修改nginx配置 中的 root 目录，就可以自动续签。否则续签会失败。
> 
> 手动续约是否有简单教程，谢谢

这个应该就是oneinstack使用的工具。你可以研究学习一下。
https://github.com/acmesh-official/acme.sh/wiki/%E8%AF%B4%E6%98%8E
