### ISSUE TITLE
Ubuntu 18.04 Upgrade OpenResty failed!

### ISSUE THREAD

**Issue by beikege** [oneinstack/oneinstack#317]
~/oneinstack/upgrade.sh

What Are You Doing?
	 1. Upgrade Nginx/Tengine/OpenResty
	 2. Upgrade Apache
	 3. Upgrade Tomcat
	 4. Upgrade MySQL/MariaDB/Percona
	 5. Upgrade PHP
	 6. Upgrade Redis
	 7. Upgrade Memcached
	 8. Upgrade phpMyAdmin
	 9. Upgrade OneinStack latest
	10. Upgrade acme.sh latest
	 q. Exit

Please input the correct option: 1

Current OpenResty Version: 1.15.8.3

Please input upgrade OpenResty Version(default: 1.17.8.1):1.17.8.1
...
...
...
-L/root/oneinstack/src/openresty-1.17.8.1/build/luajit-root/usr/local/openresty/luajit/lib -L/root/oneinstack/src/openresty-1.17.8.1/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -ljemalloc -Wl,-u,pcre_version -Wl,--require-defined=pcre_version -Wl,-E -Wl,--require-defined=pcre_version -Wl,-E -ldl -lpthread -lcrypt -L/root/oneinstack/src/openresty-1.17.8.1/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L/root/oneinstack/src/openresty-1.17.8.1/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl /root/oneinstack/src/openresty-1.17.8.1/../pcre-8.44/.libs/libpcre.a /root/oneinstack/src/openresty-1.17.8.1/../openssl-1.1.1g/.openssl/lib/libssl.a /root/oneinstack/src/openresty-1.17.8.1/../openssl-1.1.1g/.openssl/lib/libcrypto.a -ldl -lpthread -lz \
-Wl,-E
make[2]: Leaving directory '/root/oneinstack/src/openresty-1.17.8.1/build/nginx-1.17.8'
make[1]: Leaving directory '/root/oneinstack/src/openresty-1.17.8.1/build/nginx-1.17.8'
Upgrade OpenResty failed!

**Comment by oneinstack** [comment]
升级oneinstack之后执行升级试试？

**Comment by beikege** [comment]
上面的操作是先升级oneinstack到最新,然后在执行的OpenResty升级.

**Comment by juicechu** [comment]
我发现把 configure 最后参数 --with-ld-opt='-ljemalloc -Wl,-u,pcre_version' 去掉就可以。我没有深入研究原因，这个参数好像是用于优化编译速度

**Comment by juicechu** [comment]
修复 https://github.com/oneinstack/oneinstack/pull/318

**Comment by oneinstack** [comment]
@juicechu THX

**Comment by beikege** [comment]
感谢

**Comment by juicechu** [comment]
openresty 编译建议先安装 jemalloc 依赖库
for ubuntu `apt install libjemalloc-dev`

**Comment by oneinstack** [comment]
@juicechu 默认已经源码编译安装了jemalloc
