### ISSUE TITLE
LetsEncrypt acmev1 API disabled.

### ISSUE THREAD

**Issue by kissinsight** [oneinstack/oneinstack#319]
new-authz error: {"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Validations for new domains are disabled in the V1 API (https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430)","status": 403}

Upgrade to LetsEncrypt ACMEv2.

**Comment by oneinstack** [comment]
Try:
```
acme.sh --upgrade
```

**Comment by kissinsight** [comment]
Thanks. Now it's work 5n.
