### ISSUE TITLE
oneinstack/include/ioncube.sh broken 

### ISSUE THREAD

**Issue by Dj-jom2x** [oneinstack/oneinstack#320]
Download ioncube...
[ioncube_loaders_lin_x86-64.tar.gz] found
/bin/mv: cannot stat 'ioncube/ioncube_loader_lin_7.4.so': No such file or directory
[xprober.php] found

**Comment by oneinstack** [comment]
Try again!
```
./install.sh --php_extensions ioncube
```

**Comment by Dj-jom2x** [comment]
yeah that's what I execute.. I install it manually instead of by following that script code steps.

**Comment by oneinstack** [comment]
Fixed
