### ISSUE TITLE
install.sh --mphp_ver 74 無法安裝PHP7.4

### ISSUE THREAD

**Issue by alanchang15** [oneinstack/oneinstack#328]
install.sh --mphp_ver 74 無法安裝PHP7.4

**Comment by alanchang15** [comment]
install.sh --mphp_ver 7.4
上述指令無法使用

**Comment by oneinstack** [comment]
Fixed https://github.com/oneinstack/oneinstack/commit/6c2d5d9280b5acf742726c82cf90ee28a2c2a68b
