### ISSUE TITLE
Can oneinstack be installed on AliyunLinux OS?

### ISSUE THREAD

**Issue by superitgroup** [oneinstack/oneinstack#333]
Got the error message:

Does not support this OS, Please install CentOS 6+,Debian 8+,Ubuntu 14+
Killed

Can we install oneinstack on AliyunLinux?

**Comment by zhaixing** [comment]
我也遇到类似的问题 ，希望作者能够看一下

**Comment by zhaixing** [comment]
[root@host1 oneinstack]# cat /proc/version
Linux version 4.19.91-21.al7.x86_64 (mockbuild@koji-aliyun011016174077.na61) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)) #1 SMP Wed Sep 2 19:47:49 CST 20
20

uname -a
Linux host1 4.19.91-21.al7.x86_64 #1 SMP Wed Sep 2 19:47:49 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oneinstack** [comment]
Fixed https://github.com/oneinstack/oneinstack/commit/7ffbd2fd5562773d1dbddf3976c6ed416d45c72e
