### ISSUE TITLE
mariadb-10.5.6升级10.5.8备份时报错

### ISSUE THREAD

**Issue by liwemhao** [oneinstack/oneinstack#336]
mysqldump: Got error: 1449: "The user specified as a definer ('mariadb.sys'@'localhost') does not exist" when using LOCK TABLES

[root@localhost ~]# mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 825
Server version: 10.5.6-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
8 rows in set (0.000 sec)

MariaDB [(none)]> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mysql]> show tables;
+---------------------------+
| Tables_in_mysql           |
+---------------------------+
| column_stats              |
| columns_priv              |
| db                        |
| event                     |
| func                      |
| general_log               |
| global_priv               |
| gtid_slave_pos            |
| help_category             |
| help_keyword              |
| help_relation             |
| help_topic                |
| index_stats               |
| innodb_index_stats        |
| innodb_table_stats        |
| plugin                    |
| proc                      |
| procs_priv                |
| proxies_priv              |
| roles_mapping             |
| servers                   |
| slow_log                  |
| table_stats               |
| tables_priv               |
| time_zone                 |
| time_zone_leap_second     |
| time_zone_name            |
| time_zone_transition      |
| time_zone_transition_type |
| transaction_registry      |
| user                      |
+---------------------------+
31 rows in set (0.001 sec)

MariaDB [mysql]> select * from user;
ERROR 1449 (HY000): The user specified as a definer ('mariadb.sys'@'localhost') does not exist
MariaDB [mysql]> Bye

**Comment by liwemhao** [comment]
哦豁，完蛋，因为oneinstack说备份成功，我就没管这个提示升级到10.5.8，有个数据库没了，还有两个不能连接不能登录，可能没备份完全

**Comment by liwemhao** [comment]
那两个数据库是用户没了，手动创建用户后又能使用了，但不知道有没有备份全。。。。
phpmyadmin也上不去了
![QQ截图20201118110514](https://user-images.githubusercontent.com/30626007/99477672-f572c880-298d-11eb-93b7-cd7cc08883ea.png)

**Comment by liwemhao** [comment]
重装系统重新安装oneinstack后，mariadb还是有这个错误
系统Centos8
安装命令./install.sh --apache_option 1 --apache_mpm_option 1 --apache_mode_option 1 --php_option 9 --phpcache_option 1 --php_extensions ioncube,imagick,fileinfo,imap,ldap,redis,memcached --phpmyadmin  --db_option 5 --dbinstallmethod 1 --dbrootpwd oneinstack --redis  --memcached  --reboot

**Comment by oneinstack** [comment]
备份在/data/ 下，有测试机器 吗？

**Comment by liwemhao** [comment]
什么叫测试机器？装好后默认有定时备份的吗？因为没什么重要的东西我就删掉快照了，但应该都备份失败的，装好之后查看mysql.user就会出错。
香港VPS配置：1核，1G内存，2G swap，38G硬盘，BIOS引导，用CentOS-8.2.2004-x86_64-boot.iso干净安装，选择的软件是Server，没有GUI，安装后仅修改ssh端口，关闭selinux，然后安装oneinstack
用vmware模拟，仅安装mariadb，因为10.5.6的链接已经失效了，version.txt里我修改成10.5.8，装好后./upgrade升级mariadb，备份依旧出错
Starting MariaDB backup......
mysqldump: Got error: 1449: "The user specified as a definer ('mariadb.sys'@'localhost') does not exist" when using LOCK TABLES
MariaDB backup success, Backup file: /root/oneinstack/src/DB_all_backup_20201120.sql
打开DB_all_backup_20201120.sql，内容：
-- MariaDB dump 10.18  Distrib 10.5.8-MariaDB, for Linux (x86_64)
--
-- Host: localhost    Database: 
-- ------------------------------------------------------
-- Server version	10.5.8-MariaDB-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Current Database: `mysql`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `mysql` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `mysql`;

**Comment by liwemhao** [comment]
/data/backup出现一个db.log,内容
[] not exist

**Comment by oneinstack** [comment]
重新安装试试？我看是正常的

**Comment by xbclub** [comment]
这个问题是oneinstack部署的时候没有保留mariadb.sys这个用户，但是mariadb所有操作都会调用mariadb.sys,当然异常了。

**Comment by hong1999** [comment]
> 这个问题是oneinstack部署的时候没有保留mariadb.sys这个用户，但是mariadb所有操作都会调用mariadb.sys,当然异常了。

请问要怎样解决?

**Comment by oneinstack** [comment]
已经修复！
