### ISSUE TITLE
是否支持Ubuntu20.04

### ISSUE THREAD

**Issue by BlackBoxRecorder** [oneinstack/oneinstack#341]
文档描述中写的是支持Ubuntu14~19，Ubuntu20.04安装会有什么问题吗

**Comment by oneinstack** [comment]
请尝试下，应该支持的

**Comment by BlackBoxRecorder** [comment]
Ubuntu20.04安装了，没发现有问题，不知道官方有没有在Ubuntu20.04上测试过，如果测试过的话可以改下README

**Comment by oneinstack** [comment]
Done
