### ISSUE TITLE
怎么升级PHP8？

### ISSUE THREAD

**Issue by channel168** [oneinstack/oneinstack#342]
What Are You Doing?
	 1. Upgrade Nginx/Tengine/OpenResty
	 2. Upgrade Apache
	 3. Upgrade Tomcat
	 4. Upgrade MySQL/MariaDB/Percona
	 5. Upgrade PHP
	 6. Upgrade Redis
	 7. Upgrade Memcached
	 8. Upgrade phpMyAdmin
	 9. Upgrade OneinStack latest
	10. Upgrade acme.sh latest
	 q. Exit

Please input the correct option: 5

Current PHP Version: 7.4.9

Please input upgrade PHP Version(Default: 5.5.38): 8.0.0
input error! Please only input '7.4.xx'

Please input upgrade PHP Version(Default: 5.5.38): 8.0.00
input error! Please only input '7.4.xx'

Please input upgrade PHP Version(Default: 5.5.38):

**Comment by MoeACGN** [comment]
This script does not support PHP to upgrade across major versions,
Ref https://static.oneinstack.com/images/upgrade.png (Chinese description in the lower right corner)

You can use the following command to install the second PHP (PHP 8.0) :
`~/oneinstack/install.sh --mphp_ver 80`
https://github.com/oneinstack/oneinstack/blob/dd71b2fc3dfb5f0cea0221d58562bfb81db4ed10/install.sh#L53-L54
Or uninstall the currently used PHP and install PHP 8.0.
