### ISSUE TITLE
请尽快抛弃 openssl 1.0.2

### ISSUE THREAD

**Issue by betaxab** [oneinstack/oneinstack#343]
Openssl 1.0.2 已经于 2019 年停止维护。不推荐再在新系统上安装。

经测试 PHP / Nginx 均兼容 Openssl 1.1.1，完全没有必要使用旧版本。

**Comment by xlsw** [comment]
这个问题官网有解答，1.0.2是为了编译安装PHP5时使用，nginx默认就是1.1.1的。如果你只安装的PHP7以上版本，你可以手动修改versions.txt内的"openssl_ver=1.1.1k"
