### ISSUE TITLE
我需要添加一个端口应该做?

### ISSUE THREAD

**Issue by jtnetcc** [oneinstack/oneinstack#346]
我看以前的教程
（如开启 8080 端口） 
# iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT #允许 8080 端口

service iptables save 

这个好像是不管用了，现在比如我要加个8080端口应该怎么操作?

**Comment by cnlinjie** [comment]
这个属于iptables 或者 firewalld 的问题吧，自己查教程。

**Comment by oneinstack** [comment]
现在一般云主机有安全组，iptables可不用启用。
