### ISSUE TITLE
如何在虚拟机中使用oneinstack?

### ISSUE THREAD

**Issue by niuto** [oneinstack/oneinstack#347]
我尝试过在ubuntu18.04和20.04安装oneinstack都没成功，提示联系作者。问下是不是不支持在虚拟机中使用呢？

**Comment by oneinstack** [comment]
用的什么虚拟化？

**Comment by niuto** [comment]
VirtualBox和Win10 Hyper-V [非常感谢]

**Comment by oneinstack** [comment]
VirtualBox 应该没问题，apt源切换到阿里云后，再试试

**Comment by niuto** [comment]
好，我换下源试试。非常感谢！
