### ISSUE TITLE
mariadb 10.4.13 /10.5 以上因为缺失mariadb.sys 导致 phpMyAdmin 报错

### ISSUE THREAD

**Issue by hong1999** [oneinstack/oneinstack#354]
OS: Debian 10 
phpMyAdmin: 5.0.4

由于mariadb 10.4.13以上安装时会创建一个mariadb.sys的用户来作为mysql.user的definer (https://mariadb.com/kb/en/mysqluser-table/) ，某些原因oneinstack直接安装mariadb 10.4.13以上/ 10.5所有版本的时候，mariadb.sys没有被创建，导致phpMyAdmin 的User Account Tab会显示“Not Enough Privilege To View User",就算是以root用户来登录。然后SELECT User, Host FROM mysql.user;  会显示 ERROR 1449 (HY000): The user specified as a definer ('mariadb.sys'@'localhost') does not exist. 

但是当我从10.4.12版本安装然后升级到10.4.18的时候，mariadb.sys又自动被创建了。所以是没问题的。

总结：
直接安装10.4.13以上版本，直接安装有问题。
从10.4.12升级上去没问题。
10.5全部有问题           

![image](https://user-images.githubusercontent.com/32258161/112516574-60b42780-8dd2-11eb-88d1-b09e8583ff65.png)
![image](https://user-images.githubusercontent.com/32258161/112516584-63af1800-8dd2-11eb-812d-f7c52a69b2fb.png)
![image](https://user-images.githubusercontent.com/32258161/112517366-331bae00-8dd3-11eb-8943-91cb113a5bcb.png)
![image](https://user-images.githubusercontent.com/32258161/112517380-36169e80-8dd3-11eb-853c-9d91d42fe290.png)
![image](https://user-images.githubusercontent.com/32258161/112517389-39118f00-8dd3-11eb-8efd-7c5fc4d036e8.png)
![image](https://user-images.githubusercontent.com/32258161/112517397-3b73e900-8dd3-11eb-8ec1-3f4407d06b71.png)

**Comment by oneinstack** [comment]
已经修复，感谢反馈！
