### ISSUE TITLE
安装好后没有php-fpm

### ISSUE THREAD

**Issue by maruihhy** [oneinstack/oneinstack#355]
请教一下，我安装lnmp后只有php-cgi.sock，没有php-fpm.sock。
没有安装apache tomact
请问怎么解决？

**Comment by oneinstack** [comment]
php socket位置就是：/dev/shm/php-cgi.sock 名字是由配置文件/usr/local/php/etc/php-fpm.conf 控制的
没有安装apache tomact，可再次执行./install.sh 选择需要的安装即可
