### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by da-gongren** [oneinstack/oneinstack#357]
x86 的用习惯了，好想 arm 也能用呀，什么时候能支持下 arm 的服务器

**Comment by oneinstack** [comment]
如果是用arm架构服务器，安装时候选择源码编译试试

**Comment by da-gongren** [comment]
@oneinstack 邮箱留一个，日志发你邮箱呗？装不上😂

**Comment by da-gongren** [comment]
@oneinstack 详细日志在哪看呀，就提示安装失败
![image](https://user-images.githubusercontent.com/51149477/117469595-806d6c80-af88-11eb-9d45-9d905a161292.png)


编译安装 mysql 8.0.24

**Comment by oneinstack** [comment]
已经支持
