### ISSUE TITLE
jemalloc install failed, Please contact the author!

### ISSUE THREAD

**Issue by dengchsh** [oneinstack/oneinstack#360]
[mysql-8.0.24-linux-glibc2.12-x86_64.tar.xz.md5] found
PHP common...
[libiconv-1.16.tar.gz] found
[curl-7.75.0.tar.gz] found
[mhash-0.9.9.9.tar.gz] found
[libmcrypt-2.5.8.tar.gz] found
[mcrypt-2.6.8.tar.gz] found
[freetype-2.10.1.tar.gz] found
[php-7.4.19.tar.gz] found
[argon2-20171227.tar.gz] found
[libsodium-1.0.18.tar.gz] found
[libzip-1.2.0.tar.gz] found
Download ImageMagick...
[ImageMagick-7.0.11-11.tar.gz] found
Download imagick...
[imagick-3.4.4.tgz] found
Download redis-server...
[redis-5.0.9.tar.gz] found
Download start-stop-daemon.c for CentOS...
[start-stop-daemon.c] found
Download pecl_redis for php 7.x...
[redis-5.3.4.tgz] found
Download memcached-server...
[memcached-1.6.9.tar.gz] found
Download libmemcached...
[libmemcached-1.0.18.tar.gz] found
Download pecl_memcached for php 7.x...
[memcached-3.1.5.tgz] found
Download pecl_memcache for php 7.x...
[memcache-4.0.5.2.tgz] found
Download pureftpd...
[pure-ftpd-1.0.49.tar.gz] found
Download phpMyAdmin...
[phpMyAdmin-5.1.0-all-languages.tar.gz] found
checking for xsltproc... /bin/xsltproc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether compiler is cray... no
checking whether compiler supports -std=gnu11... yes
checking whether compiler supports -Wall... yes
checking whether compiler supports -Wextra... yes
checking whether compiler supports -Wshorten-64-to-32... no
checking whether compiler supports -Wsign-compare... yes
checking whether compiler supports -Wundef... yes
checking whether compiler supports -Wno-format-zero-length... yes
checking whether compiler supports -pipe... yes
checking whether compiler supports -g3... yes
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/root/oneinstack/src/jemalloc-5.2.1':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
jemalloc install failed, Please contact the author!
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core
Killed

**Comment by oneinstack** [comment]
yum源没有配置好吧，C++依赖没有安全，执行如下：
```
yum install gcc-c++
```
