### ISSUE TITLE
i upgrade php 7.0 to 7.4 and i have this issue in phpmyadmin

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#364]
i do this commands

	./install.sh --php_option 9

	~/oneinstack/upgrade.sh --oneinstack
	~/oneinstack/install.sh --php_extensions calendar

	~/oneinstack/install.sh --php_extensions fileinfo

	./install.sh --mphp_ver 74 --phpcache_option 1 --php_extensions redis --mphp_addons

and in phpmyadmin show me this:

![SNAG-0518](https://user-images.githubusercontent.com/428820/120056600-ef2b6c00-c002-11eb-867a-fddfd0669f3e.png)

how can solve it?

**Comment by oneinstack** [comment]
```
~/oneinstack/upgrad.sh --oneinstack
~/oneinstack/upgrad.sh --phpmyadmin 5.1.0
```
