### ISSUE TITLE
how down grade MariaDB-10.5 to MariaDB-10.3

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#365]
hi im using

    ./oneinstack/install.sh --db_option 7

But is not working for me how can downgrade?

**Comment by oneinstack** [comment]
You can back up the database, uninstall MariaDB10.5, install MariaDB-10.3, and restore the database from the backup file
1. mysqldump -uroot -p --opt --databases example_db> example_db.sql
2. ~/oneinstack/uninstall.sh --mysql
3. ~/oneinstack/install.sh --db_option 7
4. mysql -uroot -p < example_db.sql
