### ISSUE TITLE
request of feature python and npm

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#371]
I put all this for run in production realese

Is possible add npm apps?

And python to
with phython2

    python2 httpsServer.py

It requires Python 2.X. Then open in your web browser https://localhost:4443.

with node

    npm install npm run dev

go to https://127.0.0.1:8000/demos/threejs/cube/index.html

**Comment by oneinstack** [comment]
Node will be supported in the future

**Comment by johnfelipe** [comment]
pls ping me in here when his ready, for do all respective test, tnks

**Comment by oneinstack** [comment]
Try again
https://github.com/oneinstack/oneinstack/commit/3964ca836a452c8768c311d0445a03daa467bc7c
```
～/oneinstack/upgrade.sh --oneinstack #upgrade oneinstack
~/oneinstack/install.sh --node   # install nodejs
```
