### ISSUE TITLE
where can view logs from ssh command prompt im using putty

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#372]
![SNAG-0648](https://user-images.githubusercontent.com/428820/121089747-35c05980-c7ad-11eb-9b65-fcb56ba32131.png)

i cant view all logs in that, where can view in your enviroment, ubuntu 20.04 and putty like ssh console
Tnks

**Comment by oneinstack** [comment]
view all logs, I don't understand, Which logs are included in these logs?

**Comment by johnfelipe** [comment]
wich logs from /home/user commands?

**Comment by oneinstack** [comment]
The ssh command is documented in /var/log/messages* , You can exec `grep euid= /var/log/messages*`
Record command log configuration file: /etc/bashrc
