### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by gz83** [oneinstack/oneinstack#373]
我在centos stream系统安装oneinstack时，提示Apache安装失败并出现以下报错信息，请问这个问题应该怎样解决？
`configure: configure: Configuring Apache Portable Runtime Utility library... configure: checking for APR-util... configure: error: the --with-apr-util parameter is incorrect. It must specify an install prefix, a build directory, or an apu-config file. make: *** No targets specified and no makefile found. Stop. Apache install failed, Please contact the author! LSB Version: :core-4.1-amd64:core-4.1-noarch Distributor ID: CentOSStream Description: CentOS Stream release 8 Release: 8 Codename: n/a Killed [root@unassigned oneinstack]# /bin/basename: missing operand Try '/bin/basename --help' for more information. cat: /proc/144963/comm: No such file or directory /bin/basename: missing operand Try '/bin/basename --help' for more information. cat: /proc/144963/comm: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory mkdir: cannot create directory ‘/usr/local/apache/conf/vhost’: No such file or directory include/apache.sh: line 139: /usr/local/apache/conf/vhost/0.conf: No such file or directory include/apache.sh: line 169: /usr/local/apache/conf/httpd.conf: No such file or directory include/apache.sh: line 188: /usr/local/apache/conf/extra/httpd-remoteip.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory ldconfig: /etc/ld.so.conf.d/kernel-ml-5.12.9-1.el8.elrepo.x86_64.conf:6: hwcap directive ignored Redirecting to /bin/systemctl start httpd.service Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.`

**Comment by MoeACGN** [comment]
I think the answer is already in the screenshot.

**Comment by gz83** [comment]
> I think the answer is already in the screenshot.

I have solved this problem, but a new problem has appeared.
`configure: 
configure: Configuring Apache Portable Runtime Utility library...
configure: 
checking for APR-util... configure: error: the --with-apr-util parameter is incorrect. It must specify an install prefix, a build directory, or an apu-config file.
make: *** No targets specified and no makefile found.  Stop.
Apache install failed, Please contact the author! 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOSStream
Description:    CentOS Stream release 8
Release:        8
Codename:       n/a
Killed
[root@unassigned oneinstack]# /bin/basename: missing operand
Try '/bin/basename --help' for more information.
cat: /proc/144963/comm: No such file or directory
/bin/basename: missing operand
Try '/bin/basename --help' for more information.
cat: /proc/144963/comm: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
mkdir: cannot create directory ‘/usr/local/apache/conf/vhost’: No such file or directory
include/apache.sh: line 139: /usr/local/apache/conf/vhost/0.conf: No such file or directory
include/apache.sh: line 169: /usr/local/apache/conf/httpd.conf: No such file or directory
include/apache.sh: line 188: /usr/local/apache/conf/extra/httpd-remoteip.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
sed: can't read /usr/local/apache/conf/httpd.conf: No such file or directory
ldconfig: /etc/ld.so.conf.d/kernel-ml-5.12.9-1.el8.elrepo.x86_64.conf:6: hwcap directive ignored
Redirecting to /bin/systemctl start httpd.service
Job for httpd.service failed because the control process exited with error code.
See "systemctl status httpd.service" and "journalctl -xe" for details.
`

**Comment by oneinstack** [comment]
@gz83 可以提供下远程我看下环境吗？我测试好像没问题 可邮件：lj2007331#gmail.com

**Comment by gz83** [comment]
> @gz83 可以提供下远程我看下环境吗？我测试好像没问题 可邮件：lj2007331#gmail.com

问题已解决，我换用debian后可以正常安装了，centos stream感觉应该时缺少一些依赖。
