### ISSUE TITLE
默认页面问题

### ISSUE THREAD

**Issue by gz83** [oneinstack/oneinstack#375]
我现在用我的服务器公网IP去访问的时候，总是会进入oneinstack的默认页面，我在网上搜索到需要在vhost.sh里面绑定IP，但是我去执行vhost.sh的时候，返回的是新建网站的选项，并没有看到绑定IP的设置。

**Comment by oneinstack** [comment]
vhost.sh 绑定域名地方也可以设置IP

**Comment by gz83** [comment]
> vhost.sh 绑定域名地方也可以设置IP

问题已解决
