### ISSUE TITLE
yum config error parsing file failed killed

### ISSUE THREAD

**Issue by tamiaO** [oneinstack/oneinstack#380]
阿里云主机，alinux 3，安装出现以下错误：yum config error parsing file failed killed

**Comment by JiNG-JiN** [comment]
我也遇到了同样的问题。使用以下命令定位了一下报错位置。

`bash -vx install.sh --nginx_option 1`

发现问题出现在\oneinstack\include\check_sw.sh 151行

`if command -v lsof >/dev/null 2>&1; then
  echo 'already initialize' > ~/.oneinstack
else
  **_echo "${CFAILURE}${PM} config error parsing file failed${CEND}"_**  #报错位置
  kill -9 $$
fi`

应该是lsof没有安装造成的，然后执行以下就解决了。
`yum install lsof`

**Comment by oneinstack** [comment]
这个是yum源没有配置好。
