### ISSUE TITLE
PHP8 install failed

### ISSUE THREAD

**Issue by wxbacy** [oneinstack/oneinstack#382]
![image](https://user-images.githubusercontent.com/20201380/126732146-af5b31ac-7749-4ff2-84b9-ba3e640fa64c.png)

**Comment by oneinstack** [comment]
iconv 依赖没有安装吧

**Comment by wxbacy** [comment]
有安装，我选择php7.4可以安装成功

**Comment by oneinstack** [comment]
具体系统版本多少？

**Comment by wxbacy** [comment]
CentOS Linux release 7.9.2009 (Core)

Linux localhost.localdomain 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qinmenghua** [comment]
一样的错误。debian 10.10

**Comment by oneinstack** [comment]
测试centos7.9 centos8.4 都正常

**Comment by cklx0719** [comment]
我也是一样的提示，arm架构，ubuntu 20
奇怪的是，之前我安装的时候成功过，只选择了一个PHP8,成功了。这次有两个，一个PHP8,一个PHP72，结果失败。

**Comment by oneinstack** [comment]
再更新试试
