### ISSUE TITLE
ftp.pcre.org FTP site is no longer available.

### ISSUE THREAD

**Issue by M69W** [oneinstack/oneinstack#403]
from the [offical website](https://pcre.org/), 
> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

https://github.com/oneinstack/oneinstack/blob/dc828d84db097e1dae7befdaa1f9124a8f34a290/include/check_download.sh#L58
like: 
```diff
- src_url=https://ftp.pcre.org/pub/pcre/pcre-${pcre_ver}.tar.gz && Download_src
+ src_url=https://pilotfiber.dl.sourceforge.net/project/pcre/pcre/${pcre_ver}/pcre-${pcre_ver}.tar.gz && Download_src
```

**Comment by oneinstack** [comment]
Thank you for your feedback, Fixed[https://github.com/oneinstack/oneinstack/commit/ef2fd0c2344fbb1adfb58220807bee2c3bb7a770]
