### ISSUE TITLE
MySQL8.0下载地址出错

### ISSUE THREAD

**Issue by wolf-leo** [oneinstack/oneinstack#405]
https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/

sh中是 https://mirrors.tuna.tsinghua.edu.cn/mysql/Downloads/

Downloads 大小写

**Comment by oneinstack** [comment]
fixed, https://github.com/oneinstack/oneinstack/commit/7cdd1a817243ee2831888437a300a7b2544f3300
