### ISSUE TITLE
php8.1 安装失败 Package requirements (libargon2) were not met

### ISSUE THREAD

**Issue by yangliuan** [oneinstack/oneinstack#406]
virtualbox中centos85安装php8.1
configure: error: Package requirements (libargon2) were not met:

Package 'libargon2', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ARGON2_CFLAGS
and ARGON2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author! 

物理机 笔记本ubuntu20.04 安装php8.1

configure: error: Package requirements (libargon2) were not met:

No package 'libargon2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ARGON2_CFLAGS
and ARGON2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
[1;31mPHP install failed, Please Contact the author! [0m

**Comment by zhenxingdev** [comment]
yes oen

**Comment by clernoc** [comment]
same issue with php 8.1; php 80 can be installed without problem, but it is installed with previous php being set as default

**Comment by mark0325** [comment]
me too

**Comment by igengdu** [comment]
Debian11的VPS安装MoriaDB最新版和和php 8.1，结果出现题主同样的问题，结果安装php8.0就成功了。

**Comment by oneinstack** [comment]
fixed: https://github.com/oneinstack/oneinstack/commit/0386a8fa4028033a0621b7f5703c0ef8f606d4df
Try exec:
```
/root/oneinstack/upgrade.sh --oneinstack
/root/oneinstack/install.sh --php_option 11
```
