### ISSUE TITLE
大佬，有没有考虑支持鲲鹏服务器

### ISSUE THREAD

**Issue by jack20211101** [oneinstack/oneinstack#408]
RT.

**Comment by oneinstack** [comment]
默认选择源码安装应该是支持的

**Comment by jack20211101** [comment]
> 默认选择源码安装应该是支持的

**mysql** 尝试二进制和源码安装都失败了，最后通过[华为云](https://mirrors.huaweicloud.com/kunpeng/yum/el)官方提供的rpm包安装上了
**redis-server** 会提示开启配置：ignore-warnings ARM64-COW-BUG
其余OK
