### ISSUE TITLE
apache 处理 php，那 php 干啥用

### ISSUE THREAD

**Issue by saodis** [oneinstack/oneinstack#410]
请教大佬，这个apache 处理 php？apache 能处理 PHP，不是转发请求么？如果可以那还装 php 干啥用呢？
![image](https://user-images.githubusercontent.com/51149477/147402584-4e72e428-9451-4dd2-843d-1291b1077eba.png)

**Comment by oneinstack** [comment]
apache + mod_php 一起处理php，没有php-fpm
