### ISSUE TITLE
installing php 8 over php 7.4

### ISSUE THREAD

**Issue by clernoc** [oneinstack/oneinstack#411]
Hello, I was not able to install php 8.1, that is already reported by another user, but if I choose to install php 8.0, it is installed without any config update, I can't use `sudo update-alternatives --config php` to choose which php I want to use. If I want to have php 8 as default php, should I previously to remove php 7.X package? Or how should I configure server behavior? It is possible to change `/usr/bin/php` manually, but I doubt it is correct way of doing that.

**Comment by oneinstack** [comment]
1. fixed install php-8.1, https://github.com/oneinstack/oneinstack/commit/0386a8fa4028033a0621b7f5703c0ef8f606d4df
2. You can link the installed php version(e.g.: /usr/local/php80/bin/php ) to /usr/bin/php
