### ISSUE TITLE
mysql 8.0 无法升级 (arm64)

### ISSUE THREAD

**Issue by senioi** [oneinstack/oneinstack#414]
安装版本:8.0.27
刚刚尝试升级至8.0.28,升级完毕后mysqld彻底挂掉,
提示不是正确的可执行文件,对不起,因为服务器挂掉了紧急处理,所以没截图保存了.

**Comment by senioi** [comment]
如果升级失败,第二次升级会删除第一次升级的数据库备份(应该是覆盖了同名文件),导致备份数据为空.

**Comment by oneinstack** [comment]
arm架构服务器暂时不支持升级mysql，已经新增判断。
