### ISSUE TITLE
php 8.1 iconv does not support errno

### ISSUE THREAD

**Issue by Elypha** [oneinstack/oneinstack#415]
和 #412 大致是同样的问题
使用的代码（2月20日）里包含 [0386a8f](https://github.com/oneinstack/oneinstack/commit/0386a8fa4028033a0621b7f5703c0ef8f606d4df) fix
但是问题依然还有

```
checking if we're at 64-bit platform... yes
checking for iconv support... yes
checking for libiconv in -liconv... yes
checking if iconv is glibc's... yes
checking if iconv supports errno... no
configure: error: iconv does not support errno
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

如果把 configure 参数中 `--with-iconv=${libiconv_install_dir}` 改为 `--with-iconv` （2月8日版本的编译参数）即可通过编译

不过这样貌似是使用的系统的 iconv
```
iconv support => enabled
iconv implementation => glibc
iconv library version => 2.31
```

---
Debian 11 amd64
php 8.1 with imagick fileinfo ldap memcached bz2

**Comment by shuaiZend** [comment]
我这边对比了代码，#[0386a8f](https://github.com/oneinstack/oneinstack/commit/0386a8fa4028033a0621b7f5703c0ef8f606d4df) 并没有合并到master，官方给的包了也没有这个fix
我通过手动现在单独的文件解决了这个问题，顺利编译完成

**Comment by oneinstack** [comment]
fixed, https://github.com/oneinstack/oneinstack/commit/980abe4b10ffca2b45d78f10e90df1f8836fb947
