### ISSUE TITLE
backup_setup不支持arm架构

### ISSUE THREAD

**Issue by cklx0719** [oneinstack/oneinstack#416]
使用backup_setup进行参数配置时，设置七牛的对象存储，一直提示错误，应该是不支持arm?

![image](https://user-images.githubusercontent.com/25605487/155283006-ba586ab8-6e8e-42d3-9b69-9430a26227d7.png)

**Comment by oneinstack** [comment]
fixed,https://github.com/oneinstack/oneinstack/commit/60de439257168de6b4dff9183604b35208a533ad
