### ISSUE TITLE
RHEL 8 x86_64 使用 oneinstack 中發現的一些問題

### ISSUE THREAD

**Issue by M1Screw** [oneinstack/oneinstack#417]
1. EPEL沒有辦法正常安裝 -- 這個主要是 include/check_sw.sh 裏是用 “yum -y install epel-release” 安裝，這個指令在 RHEL 上面是無效的，需要直接用 rpm 包安裝才行
2. PowerTools 這個 repo在 RHEL 8 裏面是不存在的，需要用 “subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms” 指令啓用 RHEL 裏面等效的 CodeReady repo
3. deltarpm 在 RHEL 8 裏面的包名為 drpm ，ntpdate 這個包則是被完全移除了
4. 由於上面兩個極其重要的 repo 沒有正確安裝然後導致編譯的時候一堆依賴報錯

類似的問題在 Oracle Linux 上面使用的時候也是有，建議把 RHEL-like OS， CentOS Stream 和 RHEL 原廠 OS 在安裝依賴這塊分開處理。

**Comment by oneinstack** [comment]
您可以提交下PR吗？

**Comment by M1Screw** [comment]
這個要改的話得重寫 check_os.sh 有關 RHEL like 系統檢測的部分，然後還有 CentOS 6 相關的冗餘代碼可以清理掉，以及 Rocky Linux （CentOS 替代品）的支持都可以一并加進去，這兩天抽空寫一下吧。

**Comment by oneinstack** [comment]
[ -z "`grep -w epel /etc/yum.repos.d/*.repo`" ] && yum -y install epel-release  保留有什么问题吗？
RHEL和oracle linux 默认yum源无包名 epel-release？

**Comment by M1Screw** [comment]
主要是RHEL，有關系統自帶的包 RH 自己有個列表
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/baseos-repository
當然你在每個系統的判斷裏面都檢測一次 epel 是否安裝也是可以，不過我是覺得那樣顯得過於冗餘就沒有那樣寫

**Comment by M1Screw** [comment]
另外就是這樣用檢測文件是否存在的方式有個問題就是像 Oracle 這種本身預裝了一個 Oracle 自己編譯的 EPEL （https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/aarch64/index.html） 配置文件但是又默認沒有啓用的話，就會導致那些 EPEL 源的包裝不上去
