### ISSUE TITLE
debain下 php8.1 configure: error: iconv does not support errno 解决方案

### ISSUE THREAD

**Issue by jansion-z** [oneinstack/oneinstack#419]
我得系统是deepin基于debain，其他系统不知道什么情况但在我这，如下修改可正常安装。

位置：oneinstack/include/php-8.1.3
修改前：--with-iconv=${libiconv_install_dir}
修改后： --with-iconv-dir=${libiconv_install_dir}

如下( ...... 为省略部分 切勿直接复制 修改前注意备份)：

if [ "${Apache_main_ver}" == '22' ] || [ "${apache_mode_option}" == '2' ]; then
   ......
    --with-iconv=${libiconv_install_dir}--with-freetype --with-jpeg --with-zlib \
   ......
  else
   ......
    --with-iconv=${libiconv_install_dir}--with-freetype --with-jpeg --with-zlib \
   ......

改成

if [ "${Apache_main_ver}" == '22' ] || [ "${apache_mode_option}" == '2' ]; then
   ......
    --with-iconv-dir=${libiconv_install_dir}--with-freetype --with-jpeg --with-zlib \
   ......
  else
   ......
    --with-iconv-dir=${libiconv_install_dir} --with-freetype --with-jpeg --with-zlib \
   ......

**Comment by oneinstack** [comment]
fixed，https://github.com/oneinstack/oneinstack/commit/980abe4b10ffca2b45d78f10e90df1f8836fb947
