### ISSUE TITLE
php8.1安装fileinfo失败

### ISSUE THREAD

**Issue by easydowork** [oneinstack/oneinstack#424]
In file included from /usr/include/string.h:633:0,
from /usr/local/php81/include/php/main/../main/php_config.h:2219,
from /usr/local/php81/include/php/Zend/zend_config.h:1,
from /usr/local/php81/include/php/Zend/zend_portability.h:43,
from /usr/local/php81/include/php/Zend/zend_types.h:25,
from /usr/local/php81/include/php/Zend/zend.h:27,
from /usr/local/php81/include/php/main/php.h:31,
from /root/oneinstack/src/php-8.1.5/ext/fileinfo/libmagic/config.h:1,
from /root/oneinstack/src/php-8.1.5/ext/fileinfo/libmagic/file.h:36,
from /root/oneinstack/src/php-8.1.5/ext/fileinfo/libmagic/softmagic.c:32:
/root/oneinstack/src/php-8.1.5/ext/fileinfo/libmagic/softmagic.c:507:7: error: expected identifier or ‘(’ before ‘__extension__’
 char *strndup(const char *, size_t);
       ^
/root/oneinstack/src/php-8.1.5/ext/fileinfo/libmagic/softmagic.c:510:1: error: expected identifier or ‘(’ before ‘__extension__’
 strndup(const char *str, size_t n)
 ^
make: *** [libmagic/softmagic.lo] Error 1
make: *** Waiting for unfinished jobs....
PHP fileinfo module install failed, Please contact the author!

linux centos7

**Comment by outer199** [comment]
+1
解决方案: 修改 Makefile 文件中的 `CFLAGS` 修改为 `CFLAGS = -std=c99 -g`

**Comment by oneinstack** [comment]
参考：https://github.com/oneinstack/oneinstack/blob/master/include/pecl_fileinfo.sh，已经修复
