### ISSUE TITLE
how can add Allow Rewrite rule and openrestry without create domain is for test wordress with LAN IP

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#428]
Allow Rewrite rule? [y/n]: y

	Please input the rewrite of programme :
	wordpress,opencart,magento2,drupal,joomla,codeigniter,laravel
	thinkphp,pathinfo,discuz,typecho,ecshop,nextcloud,zblog,whmcs rewrite was exist.
	(Default rewrite: other): wordpress
	You choose rewrite=wordpress

	Allow Nginx/Tengine/OpenResty access_log? [y/n]:y

**Comment by oneinstack** [comment]
You can exec `vhost.sh`
What Are You Doing?
        1. Use HTTP Only
        2. Use your own SSL Certificate and Key
        3. Use Let's Encrypt to Create SSL Certificate and Key
        q. Exit
Please input the correct option: 1

Please input domain(example: www.example.com): 192.168.1.x

LAN IP: 192.168.1.x

**Comment by johnfelipe** [comment]
> You can exec `vhost.sh` What Are You Doing? 1. Use HTTP Only 2. Use your own SSL Certificate and Key 3. Use Let's Encrypt to Create SSL Certificate and Key q. Exit Please input the correct option: 1
> 
> Please input domain(example: [www.example.com](http://www.example.com)): 192.168.1.x
> 
> LAN IP: 192.168.1.x

dear this generate error in ip/phpmyadmin
how can solve that issue?

**Comment by oneinstack** [comment]
```
/bin/cp -R /data/wwwroot/default/phpMyAdmin /data/wwwroot/example.com/
chown -R www.www  /data/wwwroot/example.com/
```
