### ISSUE TITLE
is not possibilities create domain in localhost enviroment?

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#429]
[Thu 19 May 2022 05:41:25 AM -05] Create account key ok.
	[Thu 19 May 2022 05:41:25 AM -05] No EAB credentials found for ZeroSSL, let's get one
	[Thu 19 May 2022 05:41:26 AM -05] Registering account: https://acme.zerossl.com/v2/DV90
	[Thu 19 May 2022 05:41:41 AM -05] Registered
	[Thu 19 May 2022 05:41:41 AM -05] ACCOUNT_THUMBPRINT='Z49bhNQ3vQJNfcZkpNWhewXEkNpuMOpSiTBp6nswkio'

	Let's Encrypt Verify error! DNS problem: NXDOMAIN looking up A for formularios.felipeurrego.com
	[Thu 19 May 2022 05:41:50 AM -05] Using CA: https://acme.zerossl.com/v2/DV90
	[Thu 19 May 2022 05:41:50 AM -05] Creating domain key
	[Thu 19 May 2022 05:41:50 AM -05] The domain key is here: /root/.acme.sh/formularios.felipeurrego.com/formularios.felipeurrego.com.key
	[Thu 19 May 2022 05:41:50 AM -05] Single domain='formularios.felipeurrego.com'
	[Thu 19 May 2022 05:41:50 AM -05] Getting domain auth token for each domain
	[Thu 19 May 2022 05:42:11 AM -05] Getting webroot for domain='formularios.felipeurrego.com'
	[Thu 19 May 2022 05:42:11 AM -05] Verifying: formularios.felipeurrego.com
	[Thu 19 May 2022 05:42:19 AM -05] Processing, The CA is processing your order, please just wait. (1/30)
	[Thu 19 May 2022 05:42:29 AM -05] Processing, The CA is processing your order, please just wait. (2/30)
	[Thu 19 May 2022 05:42:40 AM -05] Processing, The CA is processing your order, please just wait. (3/30)
	[Thu 19 May 2022 05:42:51 AM -05] Processing, The CA is processing your order, please just wait. (4/30)
	[Thu 19 May 2022 05:43:02 AM -05] Processing, The CA is processing your order, please just wait. (5/30)
	[Thu 19 May 2022 05:43:21 AM -05] Processing, The CA is processing your order, please just wait. (6/30)
	[Thu 19 May 2022 05:43:34 AM -05] Processing, The CA is processing your order, please just wait. (7/30)
	[Thu 19 May 2022 05:43:45 AM -05] Processing, The CA is processing your order, please just wait. (8/30)
	[Thu 19 May 2022 05:43:56 AM -05] Processing, The CA is processing your order, please just wait. (9/30)
	[Thu 19 May 2022 05:44:05 AM -05] Processing, The CA is processing your order, please just wait. (10/30)
	[Thu 19 May 2022 05:44:15 AM -05] Processing, The CA is processing your order, please just wait. (11/30)
	[Thu 19 May 2022 05:44:25 AM -05] Processing, The CA is processing your order, please just wait. (12/30)
	[Thu 19 May 2022 05:44:33 AM -05] Processing, The CA is processing your order, please just wait. (13/30)
	[Thu 19 May 2022 05:44:42 AM -05] Processing, The CA is processing your order, please just wait. (14/30)
	[Thu 19 May 2022 05:44:52 AM -05] Processing, The CA is processing your order, please just wait. (15/30)
	[Thu 19 May 2022 05:45:02 AM -05] Processing, The CA is processing your order, please just wait. (16/30)
	[Thu 19 May 2022 05:45:11 AM -05] Processing, The CA is processing your order, please just wait. (17/30)
	[Thu 19 May 2022 05:45:24 AM -05] Processing, The CA is processing your order, please just wait. (18/30)
	[Thu 19 May 2022 05:45:35 AM -05] Processing, The CA is processing your order, please just wait. (19/30)
	[Thu 19 May 2022 05:45:47 AM -05] Processing, The CA is processing your order, please just wait. (20/30)
	[Thu 19 May 2022 05:46:01 AM -05] Processing, The CA is processing your order, please just wait. (21/30)
	[Thu 19 May 2022 05:46:13 AM -05] Processing, The CA is processing your order, please just wait. (22/30)
	[Thu 19 May 2022 05:46:26 AM -05] Processing, The CA is processing your order, please just wait. (23/30)
	[Thu 19 May 2022 05:46:30 AM -05] Processing, The CA is processing your order, please just wait. (24/30)
	[Thu 19 May 2022 05:46:43 AM -05] Processing, The CA is processing your order, please just wait. (25/30)
	[Thu 19 May 2022 05:46:53 AM -05] Processing, The CA is processing your order, please just wait. (26/30)
	[Thu 19 May 2022 05:47:08 AM -05] Processing, The CA is processing your order, please just wait. (27/30)
	[Thu 19 May 2022 05:47:20 AM -05] Processing, The CA is processing your order, please just wait. (28/30)
	[Thu 19 May 2022 05:47:35 AM -05] Processing, The CA is processing your order, please just wait. (29/30)
	[Thu 19 May 2022 05:47:46 AM -05] formularios.felipeurrego.com:Timeout
	[Thu 19 May 2022 05:47:46 AM -05] Please add '--debug' or '--log' to check more details.
	[Thu 19 May 2022 05:47:46 AM -05] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
	Error: Create Let's Encrypt SSL Certificate failed!

i edit host file 
even create in godaddy domain redirecting to my public ip
how can solve this?

**Comment by oneinstack** [comment]
The zerossl CA server seems to be unable to access formalios.felipeurrego.com to complete the verification...

**Comment by johnfelipe** [comment]
yes because is in my local ip, how can put https with your bash scripts but for local ip?

**Comment by oneinstack** [comment]
You can exec `~/oneinstack/vhost.sh --dnsapi`
More: https://oneinstack.com/faq/letsencrypt/
