### ISSUE TITLE
How can use nodejs with your stack?

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#430]

**Comment by johnfelipe** [comment]
Anyone?

**Comment by oneinstack** [comment]
Is it necessary to use nginx proxy? or?

**Comment by johnfelipe** [comment]
yes i have installed nginx not apache with install bash file

**Comment by oneinstack** [comment]
`sudo ~/oneinstack/vhost.sh --help`
`sudo ~/oneinstack/vhost.sh --proxy`  #Use proxy
