### ISSUE TITLE
Solved - unable to add brotli nginx module

### ISSUE THREAD

**Issue by RadhwaneDZ** [oneinstack/oneinstack#440]
after following some tutorials to add brotli to be able to run br files for webgl i cannot upgrade nginx with brotli 

```
cd oneinstack/src
git clone https://github.com/google/ngx_brotli.git
cd ngx_brotli
git submodule update --init
```
```
// in option.conf
nginx_modules_options='--add-module=../ngx_brotli --with-stream=dynamic'
```
i also tried to add it on oneinstack/include/nginx.sh
`./configure --prefix=${nginx_install_dir} --user=${run_user} --group=${run_group} --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=../openssl-${openssl11_ver} --add-module=../ngx_brotli --with-stream=dynamic --with-pcre=../pcre-${pcre_ver} --with-pcre-jit --with-ld-opt='-ljemalloc' `

have nginx version 1.20.2 i tried to downgrade to 1.20.1 and upgrade to 1.20.2 again with no luck

**Comment by oneinstack** [comment]
Can you provide the error message?

**Comment by RadhwaneDZ** [comment]
solved 
my bad , brotli should be added on line 61 like this 
`./configure ${nginx_configure_args} --add-module=../ngx_brotli`
