### ISSUE TITLE
mod_rewrite / Required for URL Rewriting for nginx without apache

### ISSUE THREAD

**Issue by johnfelipe** [oneinstack/oneinstack#444]
![SNAG-0020](https://user-images.githubusercontent.com/428820/178300674-c5b3c554-fbaf-4db8-b0de-8c135e69b14f.png)

how can activate mod_rewrite for nginx without apache

**Comment by oneinstack** [comment]
https://www.nginx.com/blog/creating-nginx-rewrite-rules/
