### ISSUE TITLE
在Ubuntu 22.04下,PHP7.4安装失败

### ISSUE THREAD

**Issue by jwcloverain** [oneinstack/oneinstack#446]
如题，报错内容在下方图片

![屏幕截图 2022-07-16 193220](https://user-images.githubusercontent.com/35757105/179353090-52e38a58-24bc-42df-8f7e-f3c95da35133.png)

**Comment by yangliuan** [comment]
@oneinstack 请问什么时候支持ubuntu22.04 openssl3.0安装一直失败，报同样的错误。

**Comment by yangliuan** [comment]
@M1Screw 按你的方法确实可以，奇怪的是php官方文档和configure --help没有--with-openssl-dir这个选项，写的是--with-openssl[=DIR] https://www.php.net/manual/zh/openssl.installation.php

**Comment by wslsq** [comment]
哭了，老哥你这一改，centos就用不了openssl了。

**Comment by wslsq** [comment]
> 加個 if 判斷一下 OS。不過我還是覺得很奇怪，難道Ubuntu和CentOS下面不是用的一個源碼包？爲什麽會有這種區別？

不会写shell。麻烦尽快修复下，讲真被这个修改搞了一晚上。。。😭

**Comment by oneinstack** [comment]
再试试，应该修复了
