### ISSUE TITLE
Cannot find appropriate system libraries for WITH_SSL=system.

### ISSUE THREAD

**Issue by sy3tem** [oneinstack/oneinstack#460]
RHEL9系列全线罢工。
顺带修改下check_os.sh把OracleLinux9加上去吧。
`elif [ -e "/etc/almalinux-release" ]; then
  Family=RHEL
  Platform=AlmaLinux
  grep -Eqi "release 9." /etc/almalinux-release && RHEL_ver=9
elif [ -e "/etc/rocky-release" ]; then
  Family=RHEL
  Platform=Rocky
  grep -Eqi "release 9." /etc/rocky-release && RHEL_ver=9
elif [ -e "/etc/oracle-release" ]; then
  Family=RHEL
  Platform=Oracle
  grep -Eqi "release 9." /etc/oracle-release && RHEL_ver=9`
其实 直接读取/etc/os-release不更完美么。
标题错误度娘了安装如下包 然并卵。提示已安装。
yum install –y openssl openssl-devel ncurses ncurses-devel

**Comment by oneinstack** [comment]
Done
