### ISSUE TITLE
请问怎么升级到nginx要求修复漏洞的版本啊？

### ISSUE THREAD

**Issue by yueliang1985** [oneinstack/oneinstack#465]
你好，nginx发布了一个通告，要求大家升级到nginx 1.22.1，以修复一个严重的漏洞。原文见此：https://www.oschina.net/news/214309

我看到当前oneinstack最新版的nginx版本时1.22.0，请问如何能升级到nginx建议的版本？谢谢！

**Comment by oneinstack** [comment]
```
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/upgrade.sh --nginx 1.22.1
```
