### ISSUE TITLE
oneinstack-full.tar.gz PHP80 安装脚本异常

### ISSUE THREAD

**Issue by eric1932** [oneinstack/oneinstack#469]
![CleanShot 2022-11-15 at 18 43 00@2x](https://user-images.githubusercontent.com/10938293/202055421-1e4f1436-f4c7-42c5-b880-eb3c7b7c89d3.png)

图中第24行不存在于当前最新的mirror gz中 (http://mirrors.linuxeye.com/oneinstack-full.tar.gz)

[error.log](https://github.com/oneinstack/oneinstack/files/10017132/error.log)

希望可以修复下

**Comment by oneinstack** [comment]
fixed
