### ISSUE TITLE
安装到php时报错

### ISSUE THREAD

**Issue by v2werf5ef** [oneinstack/oneinstack#470]
安装代码为：wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 10 --phpcache_option 1 --phpmyadmin  --db_option 5 --dbinstallmethod 1 --dbrootpwd password --iptables  --reboot

如下，Nginx 和 MySQL安装成功

Nginx already installed! 
MySQL already installed! 

开始安装php：

PHP common...
[libiconv-1.16.tar.gz] found
[curl-7.86.0.tar.gz] found
[mhash-0.9.9.9.tar.gz] found
[libmcrypt-2.5.8.tar.gz] found
[mcrypt-2.6.8.tar.gz] found
[freetype-2.10.1.tar.gz] found
[php-8.0.25.tar.gz] found
[argon2-20171227.tar.gz] found
[libsodium-1.0.18.tar.gz] found
[libzip-1.2.0.tar.gz] found
Download phpMyAdmin...
[phpMyAdmin-5.2.0-all-languages.tar.gz] found
include/php-8.0.sh: line 25: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): freetype-2.10.1.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 33: pushd: freetype-2.10.1: No such file or directory
include/php-8.0.sh: line 34: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): argon2-20171227.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 44: pushd: argon2-20171227: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
/bin/cp: cannot stat ‘libargon2.pc’: No such file or directory
include/php-8.0.sh: line 48: popd: directory stack empty
tar (child): libsodium-1.0.18.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 54: pushd: libsodium-1.0.18: No such file or directory
include/php-8.0.sh: line 55: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.0.sh: line 57: popd: directory stack empty
tar (child): libzip-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 63: pushd: libzip-1.2.0: No such file or directory
include/php-8.0.sh: line 64: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.0.sh: line 66: popd: directory stack empty
tar (child): php-8.0.25.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 93: pushd: php-8.0.25: No such file or directory
make: *** No rule to make target `clean'.  Stop.
include/php-8.0.sh: line 114: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
PHP install failed, Please Contact the author! 
Killed

报错如上

**Comment by v2werf5ef** [comment]
Debian11 也试了，同样的报错：

`include/php-8.0.sh: line 25: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): freetype-2.10.1.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 33: pushd: freetype-2.10.1: No such file or directory
include/php-8.0.sh: line 34: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
/bin/cp: cannot stat '/usr/local/freetype/lib/pkgconfig/freetype2.pc': No such file or directory
tar (child): argon2-20171227.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 44: pushd: argon2-20171227: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
/bin/cp: cannot stat 'libargon2.pc': No such file or directory
include/php-8.0.sh: line 48: popd: directory stack empty
tar (child): libsodium-1.0.18.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 54: pushd: libsodium-1.0.18: No such file or directory
include/php-8.0.sh: line 55: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.0.sh: line 57: popd: directory stack empty
tar (child): libzip-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 63: pushd: libzip-1.2.0: No such file or directory
include/php-8.0.sh: line 64: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.0.sh: line 66: popd: directory stack empty
tar (child): mhash-0.9.9.9.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 72: pushd: mhash-0.9.9.9: No such file or directory
include/php-8.0.sh: line 73: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.0.sh: line 75: popd: directory stack empty
tar (child): php-8.0.25.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 93: pushd: php-8.0.25: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
include/php-8.0.sh: line 114: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author!  `

**Comment by oneinstack** [comment]
fixed

**Comment by v2werf5ef** [comment]
Thanks
