### ISSUE TITLE
请教一个创建虚拟主机时，ssl证书无法申请的问题

### ISSUE THREAD

**Issue by yueliang1985** [oneinstack/oneinstack#483]
你好，我在一台主机中通过vhost.sh创建一个子域名的虚拟主机，域名是 doc.domain.com 这样子。运行到申请证书一步时，脚本只让我选择证书长度，但没有出现让我输入ssl管理员邮箱的提示，然后脚本开始申请证书，然后就是出错了，测试了很多次，都是如下的错误。

Do you want to redirect all HTTP requests to HTTPS? [y/n]: y

Please select domain cert key length.
Enter one of 2048, 3072, 4096, 8192 will issue a RSA cert.
Enter one of ec-256, ec-384, ec-521 will issue a ECC cert.

Please enter your cert key length (default 2048): ec-256
[Sat Mar 11 09:08:12 AM CST 2023] Using CA: https://acme.zerossl.com/v2/DV90
[Sat Mar 11 09:08:12 AM CST 2023] No EAB credentials found for ZeroSSL, let's get one
[Sat Mar 11 09:08:12 AM CST 2023] acme.sh is using ZeroSSL as default CA now.
[Sat Mar 11 09:08:12 AM CST 2023] Please update your account with an email address first.
[Sat Mar 11 09:08:12 AM CST 2023] acme.sh --register-account -m my@example.com
[Sat Mar 11 09:08:12 AM CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Sat Mar 11 09:08:12 AM CST 2023] Please add '--debug' or '--log' to check more details.
[Sat Mar 11 09:08:12 AM CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
Error: Create Let's Encrypt SSL Certificate failed! 

请问这是什么原因？如何解决呢？谢谢！

**Comment by oneinstack** [comment]
```
~/oneinstack/upgrade.sh --oneinstack
~/oneinstack/vhost.sh.sh 
```
