### ISSUE TITLE
官网的安装包被挂马

### ISSUE THREAD

**Issue by skiden** [oneinstack/oneinstack#487]
官网下载的http://mirrors.linuxeye.com/oneinstack-full.tar.gz  这个安装包被挂马了
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/3196984/234016475-ce4e8ca4-7779-4d5f-80a6-f3f96b289e7c.png">

**Comment by oneinstack** [comment]
是从香港节点下载的吗？

**Comment by skiden** [comment]
> 是从香港节点下载的吗？

不清楚是哪个节点，下载地址就是上面那个

**Comment by NotMings** [comment]
确实，最近安装的可以检查下 `/var/local/` 有没有相关的文件

**Comment by NotMings** [comment]
> 是从香港节点下载的吗？

希望以后可以写出文件的md5方便校验

**Comment by keysLo** [comment]
> 

是的，从香港的网络下的有马，解压下来是加密的无法读取内容

**Comment by keysLo** [comment]
这个是异常文件的md5
# md5sum oneinstack-full.tar.gz 
e7db62cee258831ff69d1216e114c412  oneinstack-full.tar.gz
美国现在发icmp 或者https似乎也是走香港
ping mirrors.linuxeye.com
PING mirrors.linuxeye.com (8.218.47.18) 56(84) bytes of data.
64 bytes from 8.218.47.18 (8.218.47.18): icmp_seq=1 ttl=46 time=208 ms
64 bytes from 8.218.47.18 (8.218.47.18): icmp_seq=2 ttl=46 time=208 ms
64 bytes from 8.218.47.18 (8.218.47.18): icmp_seq=3 ttl=46 time=209 ms

**Comment by NotMings** [comment]
> > 
> 
> 是的，从香港的网络下的有马，解压下来是加密的无法读取内容

不只是香港，国内的一样的

**Comment by keysLo** [comment]
> > > 
> > 
> > 
> > 是的，从香港的网络下的有马，解压下来是加密的无法读取内容
> 
> 不只是香港，国内的一样的

IP v6的正常，IP v4的被挂马了
# wget http://mirrors.linuxeye.com/oneinstack-full.tar.gz
--2023-04-30 23:58:44--  http://mirrors.linuxeye.com/oneinstack-full.tar.gz
Resolving mirrors.linuxeye.com (mirrors.linuxeye.com)... 2600:3c01::f03c:91ff:fe2a:d389, 8.218.47.18
Connecting to mirrors.linuxeye.com (mirrors.linuxeye.com)|2600:3c01::f03c:91ff:fe2a:d389|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 407930995 (389M) [application/octet-stream]
Saving to: ‘oneinstack-full.tar.gz’

oneinstack-full.tar.gz                            100%[=============================================================================================================>] 389.03M  14.7MB/s    in 28s     

2023-04-30 23:59:13 (13.9 MB/s) - ‘oneinstack-full.tar.gz’ saved [407930995/407930995]
# md5sum oneinstack-full.tar.gz 
b2947bac8cb66d54fcd90d30e406598f  oneinstack-full.tar.gz

**Comment by keysLo** [comment]
> 是从香港节点下载的吗？

非IP v6下载都有这个问题，http://mirrors.linuxeye.com/oneinstack-full.tar.gz

**Comment by i5ea** [comment]
刚刚测试了，确实是被挂马了，137行

**Comment by Masterain98** [comment]
检查了一下。北美网络环境下，4月28日上午（国内时间29日）下载的还是没有问题的，现在下载同样是挂马版本。
![image](https://user-images.githubusercontent.com/10614984/235407834-2747a32f-2fe7-4b50-b805-741adf738bdd.png)

**Comment by SycAlright** [comment]
简单流程：
0. 执行 ./load linux@QWE
1. 程序会检查是否RedHat，目前只针对RedHat系列，debian/ubuntu系列不执行后续
2. 下载 s.jpg 并释放到 /var/crond/ 目录，释放文件 cr.jpg 和 install可执行
3. 执行 ./install 释放 cr.jpg 到 cr目录，文件：ba、cr、snc、libaudit.so.2，并注册服务
4. 后面就是日常操作，取得控制权，成为rbq.

**Comment by i5ea** [comment]
挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉

**Comment by cddqssc** [comment]
> 挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉

免费的是这样的

**Comment by JamCh01** [comment]
> 挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉

pr welcome

**Comment by i5ea** [comment]
> > 挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉
> 
> pr welcome

你PR一个看看？
你都没搞清楚是在哪里出了问题吧？

**Comment by xj233** [comment]
在https://oneinstack.com/download/中使用dropbox的链接，
即 [https://www.dropbox.com/s/iampc7prd9y7cqf/oneinstack-full.tar.gz](https://www.dropbox.com/s/iampc7prd9y7cqf/oneinstack-full.tar.gz )
用IPv4下载的包md5校验码也为
`b2947bac8cb66d54fcd90d30e406598f`

**Comment by Masterain98** [comment]
> > 挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉
> 
> pr welcome

库里的脚本是没有问题的，问题在于分发过程中，属于IT的问题。就像你的主页用的是VMWare自签证书，除了你作为站点管理员以外，谁都没法解决。你这一句完全就是不看问题纯宣泄。

**Comment by JamCh01** [comment]
> > > 挂马这么严重的事情，作者还不抓紧处理，作者好像一点都不紧张，无所谓的感觉
> > 
> > 
> > pr welcome
> 
> 你PR一个看看？ 你都没搞清楚是在哪里出了问题吧？

分发出了问题，那么合理的解决方案是如何解决分发层面的问题，而不是抱怨开发者不作为

**Comment by zelin44913** [comment]
从哪里查看下载的安装包是否有问题？  哪个文件， 或者哪个关键字？ 
执行  grep -r "cnoneinstack" oneinstack 
未找到内容

**Comment by i5ea** [comment]
/root/oneinstack/include/openssl.sh
137行

**Comment by farson2020** [comment]
看评论实属逆天了。。。
项目官网分发被挂马这么多天 有人吐槽开发者不作为 这也有人洗？
正常不是立马下架节点避免更多受害者出现吗？
官方分流不归开发者管？那广告赞助就归开发者管？

**Comment by i5ea** [comment]
> 在 https://oneinstack.com/download/ 中使用dropbox的链接， 即 https://www.dropbox.com/s/iampc7prd9y7cqf/oneinstack-full.tar.gz 用IPv4下载的包md5校验码也为 `b2947bac8cb66d54fcd90d30e406598f`

dropbox版本的
MD5: [b2947bac8cb66d54fcd90d30e406598f]

官网链接分发挂马的
MD5: [fc897d5abba2dbff00fb6b88da878ba8]

两个MD5不一样，你似乎搞错了

**Comment by oneinstack** [comment]
不好意思，项目一直在维护，最近香港分发节点被挂马，已于28号下午14点修复，正常md5为b2947bac8cb66d54fcd90d30e406598f，有问题为fc897d5abba2dbff00fb6b88da878ba8。

**Comment by xxxsen** [comment]
> 最近香港分发节点（IP：8.218.47.18，已下线）被挂马（`oneinstack/include/openssl.sh` 137 行cnoneinstack.com 域名），已于2023-04-28 14:45修复，有问题oneinstack-full.tar.gz md5为 fc897d5abba2dbff00fb6b88da878ba8，其余均为发现问题(md5sum b2947bac8cb66d54fcd90d30e406598f 为2023-04-28 14:45强制覆盖版本)，带来不便敬请谅解。
> 
> 如果不放心可执行以下命令查看：
> 
> ```
> grep -R cnoneinstack.com ./oneinstack/
> ```
> 
> 如发现包含相关代码行建议重装系统，如未发现不影响服务器运行。

这种情况，不应该在项目的readme/官网里面置说明下吗？例如影响持续时间和范围什么的，直接在issues里面回复，压根没几个人能看到，你回复里面提到的这个md5 fc897d5abba2dbff00fb6b88da878ba8 也是错的，这个昨晚测试的时候就是这个md5，但是挂马的代码已经被清理掉了。

**Comment by oneinstack** [comment]
@xxxsen 已经更新再：https://oneinstack.com/download/

**Comment by keysLo** [comment]
> @oneinstack 官网自动安装生成的脚本用的仍然是 HTTP 链接，能否增加选择下载源的选项？Dropbox 和 sourceforge 都是支持直接 `wget` 的。 同理脚本中[更新 oneinstack 的链接](https://github.com/oneinstack/oneinstack/blob/1584442761d79da88c25b8e0a2692897dc4ae599/include/upgrade_oneinstack.sh#LL13C72-L13C72)也应该提供 HTTPS 的选项

有需要可以自己加s，http https都可以请求

**Comment by Masterain98** [comment]
> > @oneinstack 官网自动安装生成的脚本用的仍然是 HTTP 链接，能否增加选择下载源的选项？Dropbox 和 sourceforge 都是支持直接 `wget` 的。 同理脚本中[更新 oneinstack 的链接](https://github.com/oneinstack/oneinstack/blob/1584442761d79da88c25b8e0a2692897dc4ae599/include/upgrade_oneinstack.sh#LL13C72-L13C72)也应该提供 HTTPS 的选项
> 
> 有需要可以自己加s，http https都可以请求

我是希望HTTPS是**默认选项** ；另外我也提到了更新脚本中用的也是 HTTPS

**Comment by i5ea** [comment]
> > > @oneinstack 官网自动安装生成的脚本用的仍然是 HTTP 链接，能否增加选择下载源的选项？Dropbox 和 sourceforge 都是支持直接 `wget` 的。 同理脚本中[更新 oneinstack 的链接](https://github.com/oneinstack/oneinstack/blob/1584442761d79da88c25b8e0a2692897dc4ae599/include/upgrade_oneinstack.sh#LL13C72-L13C72)也应该提供 HTTPS 的选项
> > 
> > 
> > 有需要可以自己加s，http https都可以请求
> 
> 我是希望HTTPS是**默认选项** ；另外我也提到了更新脚本中用的也是 HTTPS

不明白，都什么年代了，还不默认配置https，估计是怕麻烦吧

**Comment by Masterain98** [comment]
> > > > @oneinstack 官网自动安装生成的脚本用的仍然是 HTTP 链接，能否增加选择下载源的选项？Dropbox 和 sourceforge 都是支持直接 `wget` 的。 同理脚本中[更新 oneinstack 的链接](https://github.com/oneinstack/oneinstack/blob/1584442761d79da88c25b8e0a2692897dc4ae599/include/upgrade_oneinstack.sh#LL13C72-L13C72)也应该提供 HTTPS 的选项
> > > 
> > > 
> > > 有需要可以自己加s，http https都可以请求
> > 
> > 
> > 我是希望HTTPS是**默认选项** ；另外我也提到了更新脚本中用的也是 HTTPS
> 
> 不明白，都什么年代了，还不默认配置https，估计是怕麻烦吧

可能是怕烧钱？UPYUN 的 HTTPS 价格确实明显高于其它CDN厂商。我考虑了这点，所以说了能否**给出选择其它下载源的选项**，Dropbox 和 sourceforge 肯定是 HTTPS的

**Comment by g0mxxm** [comment]
哪位兄弟有”osk.jpg"这个样本，或者MD5，想看看干了啥，现在获取不到了
