### ISSUE TITLE
QCloud备份

### ISSUE THREAD

**Issue by NotMings** [oneinstack/oneinstack#488]
腾讯云备份不需要-u参数

**Comment by oneinstack** [comment]
```
coscmd config --help
usage: coscmd config [-h] -a SECRET_ID -s SECRET_KEY [-t TOKEN] -b BUCKET (-r REGION | -e ENDPOINT) [-m MAX_THREAD]
                     [-p PART_SIZE] [--retry RETRY] [--timeout TIMEOUT] [-u APPID] [--verify VERIFY] [--do-not-use-ssl]
                     [--anonymous]

optional arguments:
  -h, --help            show this help message and exit
  -a SECRET_ID, --secret_id SECRET_ID
                        Specify your secret id
  -s SECRET_KEY, --secret_key SECRET_KEY
                        Specify your secret key
  -t TOKEN, --token TOKEN
                        Set x-cos-security-token header
  -b BUCKET, --bucket BUCKET
                        Specify your bucket
  -r REGION, --region REGION
                        Specify your region
  -e ENDPOINT, --endpoint ENDPOINT
                        Specify COS endpoint
  -m MAX_THREAD, --max_thread MAX_THREAD
                        Specify the number of threads (default 5)
  -p PART_SIZE, --part_size PART_SIZE
                        specify min part size in MB (default 1MB)
  --retry RETRY         specify retry times
  --timeout TIMEOUT     specify request timeout
  -u APPID, --appid APPID
                        Specify your appid
  --verify VERIFY       Specify your encryption method
  --do-not-use-ssl      Use http://
  --anonymous           Anonymous operation
```

**Comment by NotMings** [comment]
> coscmd config --help 需要-u指定appid吧
> 
> ```
> coscmd config --help
> usage: coscmd config [-h] -a SECRET_ID -s SECRET_KEY [-t TOKEN] -b BUCKET (-r REGION | -e ENDPOINT) [-m MAX_THREAD]
>                      [-p PART_SIZE] [--retry RETRY] [--timeout TIMEOUT] [-u APPID] [--verify VERIFY] [--do-not-use-ssl]
>                      [--anonymous]
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -a SECRET_ID, --secret_id SECRET_ID
>                         Specify your secret id
>   -s SECRET_KEY, --secret_key SECRET_KEY
>                         Specify your secret key
>   -t TOKEN, --token TOKEN
>                         Set x-cos-security-token header
>   -b BUCKET, --bucket BUCKET
>                         Specify your bucket
>   -r REGION, --region REGION
>                         Specify your region
>   -e ENDPOINT, --endpoint ENDPOINT
>                         Specify COS endpoint
>   -m MAX_THREAD, --max_thread MAX_THREAD
>                         Specify the number of threads (default 5)
>   -p PART_SIZE, --part_size PART_SIZE
>                         specify min part size in MB (default 1MB)
>   --retry RETRY         specify retry times
>   --timeout TIMEOUT     specify request timeout
>   -u APPID, --appid APPID
>                         Specify your appid
>   --verify VERIFY       Specify your encryption method
>   --do-not-use-ssl      Use http://
>   --anonymous           Anonymous operation
> ```

https://cloud.tencent.com/document/product/436/10976
设置了appid后反而会导致报错“找不到存储桶”
我是修改了
 `${python_install_dir}/bin/coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -r ${REGION} -b ${COS_BUCKET} > /dev/null 2>&1`
并且更改了
```
if [[ ${COS_BUCKET} =~ "-${APPID}"$ ]]; then
  COS_BUCKET=${COS_BUCKET}
  else
  [ -z "${COS_BUCKET}" ] && continue
  echo
  COS_BUCKET=${COS_BUCKET}-${APPID}
fi
```
改为
```
[ -z "${COS_BUCKET}" ] && continue
echo
```
才成功调用`coscmd list`

**Comment by NotMings** [comment]
主要是腾讯云支持子用户使用密钥，在主用户创建存储桶后，存储桶的名字便固定下来。此时的`BucketName-APPID`与子用户id并不相同。所以建议不设置appid，直接使用`SECRET_ID` 和`SECRET_ID`

**Comment by oneinstack** [comment]
已经更新包，谢谢反馈。
