### ISSUE TITLE
MariaDB 10.6.13 清华源下载地址失效

### ISSUE THREAD

**Issue by samshuai** [oneinstack/oneinstack#495]
![image](https://github.com/oneinstack/oneinstack/assets/1312406/e5008444-aa7a-4a38-818d-0445ca413a2b)

https://github.com/oneinstack/oneinstack/blob/main/versions.txt#L26
将版本号修改为10.6.14后可修复该问题

**Comment by oneinstack** [comment]
fixed,thx!
