### ISSUE TITLE
自动安装安装不了，报错！

### ISSUE THREAD

**Issue by lewuzzx** [oneinstack/oneinstack#504]
报错显示：-bash: ./oneinstack/install.sh: Permission denied
显示权限被拒绝
我使用的是Debian11系统
在昨天下午都可以安装，到晚上就不能安装了。
自动安装失败，只下载了oneinstack文件，后面的安装不了了

**Comment by oneinstack** [comment]
fixed

**Comment by lewuzzx** [comment]
> 固定的

是我服务器的问题吗？
