### ISSUE TITLE
Incorrect MariaDB URL in include/upgrade_db.sh

### ISSUE THREAD

**Issue by KozakaiAya** [oneinstack/oneinstack#509]
https://github.com/oneinstack/oneinstack/blob/7089eaef4e4ea3cf8e48a752bd1a8857534c83c7/include/upgrade_db.sh#L37

The URL for downloading MariaDB in `upgrade_db.sh` is not correct. Currently, it is pointed to `https://downloads.mariadb.org/f`, but the correct URL prefix should be `https://archive.mariadb.org`.

The URL in `check_download.sh` is correct. 

https://github.com/oneinstack/oneinstack/blob/7089eaef4e4ea3cf8e48a752bd1a8857534c83c7/include/check_download.sh#L277

**Comment by oneinstack** [comment]
fixed
