### ISSUE TITLE
oneinstack一键脚本似乎已经被一家名叫“金华市矜贵网络科技有限公司”的公司收购，该公司运营有一个盗版MAC软件网站

### ISSUE THREAD

**Issue by i5ea** [oneinstack/oneinstack#510]
消息来源：https://twitter.com/landiantech/status/1709226985334214932

oneinstack.com 的备案号9月27号变更为：浙ICP备2023007596号-4 

与该公司运营的盗版MAC软件网站的备案号：浙ICP备2023007596号-1 一致

该公司还同时收购了军哥的lnmp.org一键脚本，lnmp.org网站下的版权信息已经变更

看来是时候寻找新的替代脚本了

**Comment by oneinstack** [comment]
与代码无关，请提交代码相关issues
