### ISSUE TITLE
是否有其它代替品

### ISSUE THREAD

**Issue by shirakun** [oneinstack/oneinstack#514]
RT
lnmp和oneinstack都没了
以后要想用lnmp环境的话只能手搓了吗
![@%V1$QFFVX%RLM86AC19PLW](https://github.com/oneinstack/oneinstack/assets/11274807/2b246d98-ade5-4d75-b754-0ef653b7a74a)

**Comment by shirakun** [comment]
> lnmp还在，还能用

但是已经有后门了

**Comment by zyimm** [comment]
> RT lnmp和oneinstack都没了 以后要想用lnmp环境的话只能手搓了吗 ![@%V1$QFFVX%RLM86AC19PLW](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) [ ![@%V1$QFFVX%RLM86AC19PLW](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) ](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) [ ](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif)



> RT lnmp和oneinstack都没了 以后要想用lnmp环境的话只能手搓了吗 ![@%V1$QFFVX%RLM86AC19PLW](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) [ ![@%V1$QFFVX%RLM86AC19PLW](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) ](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif) [ ](https://user-images.githubusercontent.com/11274807/280899929-2b246d98-ade5-4d75-b754-0ef653b7a74a.gif)

docker 走起 这年头谁还原生部署呢？

**Comment by Masterain98** [comment]
把oneinstack源换成 https://oneinstack-redirect-mirror.pages.dev/ 还能继续用

**Comment by m3cooper** [comment]
LEMP Stack：Linux、Nginx、MySQL、PHP的组合。
LAMP Stack：Linux、Apache、MySQL、PHP的组合。
EasyEngine：针对WordPress优化的Nginx、PHP和MySQL自动安装脚本。
Webinoly：专注于Nginx、PHP、MySQL和Let's Encrypt证书的一键安装脚本。

**Comment by We1eVen** [comment]
> > lnmp还在，还能用
> 
> 但是已经有后门了

用[以前的离线包](https://lnmp.club/)

**Comment by zhujitop** [comment]
> 把oneinstack源换成 https://oneinstack-redirect-mirror.pages.dev/ 还能继续用

请问这个具体怎么使用的？

**Comment by Masterain98** [comment]
> 请问这个具体怎么使用的？

在 [options.conf](https://github.com/oneinstack/oneinstack/blob/main/options.conf#L2) 内替换

**Comment by zhujitop** [comment]
> 以前的离线包

就是把
mirror_link=http://mirrors.linuxeye.com 换成
mirror_link=https://oneinstack-redirect-mirror.pages.dev
就行了？

以前没有被植入后门的老版本也要换吗？
我本地有保存过老版

**Comment by shirakun** [comment]
> ![b039d51d1c82f4d48b3cfa0012be304b_12f5b7c2-7c81-4b4c-ab14-c64b9bdef496](https://private-user-images.githubusercontent.com/21142462/305688540-140e00e4-90a0-4b41-8216-2cd37202049e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY4NDEsIm5iZiI6MTcwODMwNjU0MSwicGF0aCI6Ii8yMTE0MjQ2Mi8zMDU2ODg1NDAtMTQwZTAwZTQtOTBhMC00YjQxLTgyMTYtMmNkMzcyMDIwNDllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAxMzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMTA2NzhkNTcyMzc2ZDYyYTdmMTU5ODk1NzFiODk3YWQyMzhhNWFiYzJkMzdhOTJjNTg4ZDBjMWRlNTc5ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FapkYEOeLeJWWvqQx-dKTyuUAl8hZIGwaWvt-8-qNi8)

他的产品现在不敢用了
目前在用teddysun的lcmp
https://github.com/teddysun/lcmp

**Comment by seventeen-0107** [comment]
唉 可惜了
