### ISSUE TITLE
mirrors.oneinstack.com  没有 ioncube | sourceguardian 几个包。都没了。

### ISSUE THREAD

**Issue by ipme** [oneinstack/oneinstack#516]
`ioncube_loaders_lin_x86-64.tar.gz]` found
Download SourceGuardian...
--2023-11-12 15:06:48--  http://mirrors.oneinstack.com/oneinstack/src/loaders.linux-x86_64.tar.gz
Resolving mirrors.oneinstack.com (mirrors.oneinstack.com)... 116.211.122.1, 116.211.122.2
Connecting to mirrors.oneinstack.com (mirrors.oneinstack.com)|116.211.122.1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-12 15:06:48 ERROR 404: Not Found.

Auto download failed! You can manually download http://mirrors.oneinstack.com/oneinstack/src/loaders.linux-x86_64.tar.gz into the oneinstack/src directory.
Killed`

这个要怎么改一下，自己把包下载到 src/  目录下面了。

**Comment by Masterain98** [comment]
可以尝试这个源

https://oneinstack-redirect-mirror.pages.dev/

**Comment by oneinstack** [comment]
fixed
