### ISSUE TITLE
AWS S3 backup失效

### ISSUE THREAD

**Issue by limymy** [oneinstack/oneinstack#521]
使用AWS S3备份时，脚本输出
warning: Skipping file /data/backup/xxxxx.tgz/. File does not exist.
因为
https://github.com/oneinstack/oneinstack/blob/89f0779a4540ed0a38de8f909c1df57a5ce13b14/backup.sh#L103
https://github.com/oneinstack/oneinstack/blob/89f0779a4540ed0a38de8f909c1df57a5ce13b14/backup.sh#L234
`aws s3 sync`指令用于同步目录
参考文档：https://docs.aws.amazon.com/zh_cn/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-managing-objects-sync
```
s3 sync命令同步一个存储桶与一个目录中的内容，或者同步两个存储桶中的内容。
```
参考文档：https://docs.aws.amazon.com/zh_cn/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-managing-objects-sync

请考虑使用`aws s3 cp`或`aws s3 mv`等指令

**Comment by oneinstack** [comment]
next version will fix it
