### ISSUE TITLE
https://mirrors.oneinstack.com/oneinstack.tar.gz 无法访问

### ISSUE THREAD

**Issue by outer199** [oneinstack/oneinstack#531]
--2024-04-20 10:28:46--  (try: 2)  https://mirrors.oneinstack.com/oneinstack.tar.gz
Connecting to mirrors.oneinstack.com (mirrors.oneinstack.com)|43.152.136.177|:443... connected.
HTTP request sent, awaiting response... Read error (Success.) in headers.
Retrying.

**Comment by jack20211101** [comment]
可以试试它的海外源
https://www.dropbox.com/s/iampc7prd9y7cqf/oneinstack-full.tar.gz
http://downloads.sourceforge.net/project/oneinstack/oneinstack-full.tar.gz

**Comment by outer199** [comment]
> 可以试试它的海外源 https://www.dropbox.com/s/iampc7prd9y7cqf/oneinstack-full.tar.gz http://downloads.sourceforge.net/project/oneinstack/oneinstack-full.tar.gz

感谢 不太敢用啊 怕有毒
