### ISSUE TITLE
PHP 7.4  : PHP install failed, Please Contact the author!

### ISSUE THREAD

**Issue by turndealer** [oneinstack/oneinstack#533]
Hi installing ,

Oneinstack with 

wget -c http://mirrors.oneinstack.com/oneinstack.tar.gz && tar xzf oneinstack.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 9 --phpcache_option 1 --php_extensions imagick,fileinfo,redis,swoole --phpmyadmin  --db_option 5 --dbinstallmethod 1 --dbrootpwd l6llts53 --redis  --reboot 

On ubuntu 22

While installation it stops and gives following error 
checking whether to enable PCRE JIT functionality... yes
checking whether Intel CET is enabled... yes
checking whether to enable the SQLite3 extension... yes
checking for sqlite3 > 3.7.4... yes
checking for sqlite3_errstr in -lsqlite3... yes
checking for sqlite3_expanded_sql in -lsqlite3... yes
checking for sqlite3_load_extension in -lsqlite3... yes
checking for ZLIB support... yes
checking for zlib >= 1.2.0.4... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... no
checking whether to enable calendar conversion support... no
checking whether to enable ctype functions... yes
checking for cURL support... yes
checking for libcurl >= 7.15.5... yes
checking for SSL support in libcurl... yes
checking for libcurl linked against old openssl... no
checking for curl_easy_perform in -lcurl... no
configure: error: There is something wrong. Please check config.log for more information.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author! 

When I tried to do manually it also gave same error.
checking for curl_easy_perform in -lcurl... no
configure: error: There is something wrong. Please check config.log for more information.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author!
Killed

I have made various installations , with previous versions , is there anything bricking changes in recent updates ?

I am trying it for php 7.4, apache, nginx , mariadb 10.11

Please suggest.

**Comment by turndealer** [comment]
It happens on servers with either of the conditions 

Ubuntu 24.

or there is timeout issues due to data center’s connectivity 

For above issue we switch to another server or data Center .


Thank you !

**Comment by jvkranenburg** [comment]
@turndealer how did you solve this? I have the same on Ubuntu 22/24 and Debian 12.....

**Comment by turndealer** [comment]
The happens if there is timeout and connectivity issues.

Nothing could solve this as server was timing out .

It’s best suggested ditch the host or data Center and switch to other server .
