### ISSUE TITLE
php82 安装失败

### ISSUE THREAD

**Issue by cnwyx** [oneinstack/oneinstack#534]
include/php-8.2.sh: line 55: pushd: libsodium-1.0.19: No such file or directory
include/php-8.2.sh: line 56: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): libzip-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.2.sh: line 64: pushd: libzip-1.2.0: No such file or directory
include/php-8.2.sh: line 65: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): mhash-0.9.9.9.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.2.sh: line 73: pushd: mhash-0.9.9.9: No such file or directory
include/php-8.2.sh: line 74: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
include/php-8.2.sh: line 76: popd: directory stack empty
tar (child): php-8.2.14.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.2.sh: line 94: pushd: php-8.2.14: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
include/php-8.2.sh: line 111: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author! 
Killed

- db493e2
- c308f74

**Comment by sussdorf** [comment]
yes i have the same error

**Comment by ronannc** [comment]
yes i have the same error

**Comment by S-Marouene** [comment]
the same error !

**Comment by mr-wolf-gb** [comment]
Error : `libsodium-1.0.19: No such file or directory`
Solution : 
```bash
# oneinstack working directory
$ cd src
$ sudo cp -R libsodium-stable libsodium-1.0.19
# re-run ./install.sh
```

**Comment by oneinstack** [comment]
fixed
