### ISSUE TITLE
install php-8.3 error

### ISSUE THREAD

**Issue by insistent-afk** [oneinstack/oneinstack#535]
CentOS 9 PHP 8.3.2

> Building with optimizations for native
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native  src/argon2.c src/core.c src/blake2/blake2b.c src/thread.c src/encoding.c src/opt.c src/run.c -o argon2
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native -shared -fPIC -fvisibility=hidden -DA2_VISCTL=1  -Wl,-soname,libargon2.so.1 src/argon2.c src/core.c src/blake2/blake2b.c src/thread.c src/encoding.c src/opt.c -o libargon2.so.1
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/argon2.o src/argon2.c
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/core.o src/core.c
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/blake2/blake2b.o src/blake2/blake2b.c
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/thread.o src/thread.c
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/encoding.o src/encoding.c
cc -std=c89 -O3 -Wall -g -Iinclude -Isrc -pthread -march=native   -c -o src/opt.o src/opt.c
ar rcs libargon2.a src/argon2.o src/core.o src/blake2/blake2b.o src/thread.o src/encoding.o src/opt.o
Building with optimizations for native
install -d /usr/include
install -m 0644 include/argon2.h /usr/include
install -d /usr/lib
install libargon2.so.1 libargon2.a /usr/lib
cd /usr/lib && ln -s libargon2.so.1 libargon2.so
install -d /usr/bin
install argon2 /usr/bin
include/php-8.3.sh: line 55: pushd: libsodium-1.0.19: No such file or directory
include/php-8.3.sh: line 56: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): libzip-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.3.sh: line 64: pushd: libzip-1.2.0: No such file or directory
include/php-8.3.sh: line 65: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): php-8.3.2.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.3.sh: line 94: pushd: php-8.3.2: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
include/php-8.3.sh: line 111: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cat install.sh >install
chmod a+x install
PHP install failed, Please Contact the author!
Killed
[root@centos1 oneinstack]#

**Comment by insistent-afk** [comment]
[how to libsodium-1.0.19: No such file or directory](https://github.com/oneinstack/oneinstack/issues/534#issuecomment-2146932595)

> checking for libcurl >= 7.29.0... no
configure: error: Package requirements (libcurl >= 7.29.0) were not met:

>Package 'libcurl', required by 'virtual:world', not found

>Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

>Alternatively, you may set the environment variables CURL_CFLAGS
and CURL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
PHP install failed, Please Contact the author!
Killed
[root@centos1 oneinstack]#

**Comment by insistent-afk** [comment]
I solved the problem by installing additional packages. 

`dnf install libcurl-devel`

**Comment by oneinstack** [comment]
fixed
