### ISSUE TITLE
nginx一直装不上

### ISSUE THREAD

**Issue by Prajna11** [oneinstack/oneinstack#537]
![微信截图_20240707221605](https://github.com/oneinstack/oneinstack/assets/40759634/95569beb-28b5-46cb-9b01-5780418bcb07)

提示成功，却没有安装成功，目录都找不到

**Comment by mugua** [comment]
是的，官网自动安装存在2个问题：
1：Ngnix或OpenResty安装不了，需要自己去Nginx或OpenResty下载安装包，修改version文件。
2：Php8.3在安装libsodim时，解压后的文件名其实是 -stable，不是-1.0.19，因此需要修改php8.3的设置。具体参照另一个bug反馈。

**Comment by oneinstack** [comment]
fixed
