### ISSUE TITLE
internal server 500 error

### ISSUE THREAD

**Issue by hsynclb** [oneinstack/oneinstack#539]
![image](https://github.com/user-attachments/assets/74046867-80a4-415d-81ae-e4a8f081ca85)

https://mirrors.oneinstack.com/oneinstack/src/nginx-1.24.0.tar.gz

**Comment by huobo90** [comment]
我也遇到了同样的问题，貌似很多包都出现了500，我一开始尝试解决，结果发现每解决一个都会出现新的500，就放弃了

**Comment by yueim** [comment]
有个开源镜像方案，适合对安全性有疑虑的人：

https://github.com/dalao-org/oneinstack-mirror-generator

**Comment by oneinstack** [comment]
fixed
