### ISSUE TITLE
oneinstack自建cdn多个资源出现500，如icu4c-63_1-src.tgz、pcre-8.45.tar.gz、jemalloc-5.3.0.tar.bz2等

### ISSUE THREAD

**Issue by huobo90** [oneinstack/oneinstack#540]
无论是交互安装还是自动安装都无法完成，多个资源的链接出现500错误。

最开始我尝试自己解决，遇到某个资源报错中断，我就单独去download哪个资源，结果发现不断的有资源不可用，不知道要解决多少才是个头。

附几个报错的链接，这是剪切板里找到的，其他的因为ssh窗口的关闭已经看不到了，而且我遇到的这几个肯定也不是全部。

`Auto download failed! You can manually download https://mirrors.oneinstack.com/oneinstack/src/icu4c-63_1-src.tgz into the oneinstack/src directory.

Auto download failed! You can manually download https://mirrors.oneinstack.com/oneinstack/src/pcre-8.45.tar.gz into the oneinstack/src directory.

Auto download failed! You can manually download https://mirrors.oneinstack.com/oneinstack/src/jemalloc-5.3.0.tar.bz2 into the oneinstack/src directory.`

**Comment by cyrixiii** [comment]
是的，前几天还正常安装过，今天安装就出现500错误了

**Comment by i5ea** [comment]
我也遇到了相同的问题

**Comment by yueim** [comment]
认真看看这俩 issue，看看能不能给你点什么启发：

官网的安装包被挂马 #487

mirrors.oneinstack.com 国内完整包 含恶意代码 #511

**Comment by huobo90** [comment]
> 认真看看这俩 issue，看看能不能给你点什么启发：
> 
> * [官网的安装包被挂马 #487](https://github.com/oneinstack/oneinstack/issues/487)
> * [mirrors.oneinstack.com 国内完整包 含恶意代码 #511](https://github.com/oneinstack/oneinstack/issues/511)

oneinstack一直用了很多年了，给非常多的朋友推荐过，不夸张的讲，几乎用出了感情，oneinstack对我这样的运维小白帮助非常的大

**Comment by RyanLin28** [comment]
> 认真看看这俩 issue，看看能不能给你点什么启发：
> 
> * [官网的安装包被挂马 #487](https://github.com/oneinstack/oneinstack/issues/487)
> * [mirrors.oneinstack.com 国内完整包 含恶意代码 #511](https://github.com/oneinstack/oneinstack/issues/511)

就国内目前的现状，暂时是没有oneinstack的平替。。。供应链投毒只能说免费的代价在此吧。。。个人觉得宝塔、小皮都不大行。。。

**Comment by huobo90** [comment]
> > 认真看看这俩 issue，看看能不能给你点什么启发：
> > 
> > * [官网的安装包被挂马 #487](https://github.com/oneinstack/oneinstack/issues/487)
> > * [mirrors.oneinstack.com 国内完整包 含恶意代码 #511](https://github.com/oneinstack/oneinstack/issues/511)
> 
> 就国内目前的现状，暂时是没有oneinstack的平替。。。供应链投毒只能说免费的代价在此吧。。。个人觉得宝塔、小皮都不大行。。。

请问宝塔用起来有什么缺点？

**Comment by FreeyW** [comment]
似乎已经恢复了，大家试试

**Comment by RyanLin28** [comment]
> > > 认真看看这俩 issue，看看能不能给你点什么启发：
> > > 
> > > * [官网的安装包被挂马 #487](https://github.com/oneinstack/oneinstack/issues/487)
> > > * [mirrors.oneinstack.com 国内完整包 含恶意代码 #511](https://github.com/oneinstack/oneinstack/issues/511)
> > 
> > 
> > 就国内目前的现状，暂时是没有oneinstack的平替。。。供应链投毒只能说免费的代价在此吧。。。个人觉得宝塔、小皮都不大行。。。
> 
> 请问宝塔用起来有什么缺点？

我个人觉得广告多、如果有7-8台服务器都装宝塔，每台都要记录路径，如果就1台那是无所谓，而且宝塔小皮这种在我看来和留了后门无异
我习惯了oneinstack所有配置在命令行配置了，最早是lnmp然后到oneinstack，linux在我看来就该是一堆shell组成的东西。

**Comment by oneinstack** [comment]
fixed
